In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

base_path = "/content/drive/MyDrive/승화 토프"
files = os.listdir(base_path)

print(files)

['toyproj.ipynb', '서울시_지하철호선별_역별_승하차_인원_정보.csv', '서울시_지진대피소_현황.csv', '소상공인시장진흥공단_상가(상권)정보_서울_202512.csv', '기타', '서울시 역사마스터 정보.csv', '서울시 병의원 위치 정보.csv', '서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv']

In [ ]:
import pandas as pd

data_dict = {}

for file in files:
    if file.endswith(".csv"):
        file_path = os.path.join(base_path, file)

        print(f"\n📂 Loading: {file}")

        try:
            df = pd.read_csv(file_path, encoding='utf-8-sig')
        except:
            df = pd.read_csv(file_path, encoding='cp949')

        data_dict[file] = df

        print("shape:", df.shape)
        display(df.head())

📂 Loading: 서울시_지하철호선별_역별_승하차_인원_정보.csv
shape: (24689, 6)

       사용일자    호선명        역명  승차총승객수  하차총승객수      등록일자
0  20260314  우이신설선  4.19민주묘지    3051    2568  20260317
1  20260314    경원선        가능    5885    5536  20260317
2  20260314    8호선      가락시장    7159    7451  20260317
3  20260314    3호선      가락시장    7483    7240  20260317
4  20260314    7호선   가산디지털단지   16921   15594  20260317

📂 Loading: 서울시_지진대피소_현황.csv
shape: (1551, 11)

,피난처 ID,시도명,시군구명,시설명,상세주소,시설면적,경도,위도,구분,구분명,관리부서
0,1,서울특별시,동작구,동작고등학교 운동장,서울특별시 동작구 솔밭로 51(사당동),3246.0,126.9655,37.4820,1,지진실내구호소,070-4629-6407
1,2,서울특별시,동작구,동작초등학교 운동장,서울특별시 동작구 동작대로29길 214(사당동),2763.0,126.9768,37.4940,1,지진실내구호소,02-537-1773
2,3,서울특별시,도봉구,창림초등학교 운동장,서울특별시 도봉구 덕릉로63길 46(창동),2584.0,127.0417,37.6431,1,지진실내구호소,02-2091-5718
3,4,서울특별시,도봉구,창원초등학교 운동장,서울특별시 도봉구 해등로 103(창동),2704.0,127.0407,37.6521,1,지진실내구호소,02-2091-5779
4,5,서울특별시,도봉구,창일중학교 운동장,서울특별시 도봉구 노해로66길 60(창동),4800.0,127.0471,37.6484,1,지진실내구호소,02-2091-5678

📂 Loading: 소상공인시장진흥공단_상가(상권)정보_서울_202512.csv
shape: (534978, 39)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220804265295,60계치킨암사,선사점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1174010700105020004015779,암사동정웅빌딩,서울특별시 강동구 상암로3길 8,134877,5241,NaN,1,NaN,127.126859,37.550810
1,MA010120220809658173,성심인력공사,NaN,N1,시설관리·임대,N104,고용 알선,N10401,고용 알선업,N75110,...,1117010700100430059022991,NaN,서울특별시 용산구 한강대로 385,140821,4320,NaN,NaN,NaN,126.972240,37.552803
2,MA010120220808205276,칸토빈,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1150010800200200002002536,공항시장역,서울특별시 강서구 방화동로 30,157240,7619,NaN,1,NaN,126.810493,37.563548
3,MA010120220804370987,까치노래연습장,NaN,R1,예술·스포츠,R104,유원지·오락,R10407,노래방,R91223,...,1135010500101690179002482,NaN,서울특별시 노원구 한글비석로23길 2,139815,1682,NaN,NaN,NaN,127.071218,37.660715
4,MA010120220810170381,금빛주얼리,NaN,G2,소매,G217,시계·귀금속 소매,G21701,시계/귀금속 소매업,G47830,...,1111015100100880001000001,종로주얼리타운,서울특별시 종로구 돈화문로10길 2,110370,3138,NaN,1,NaN,126.991861,37.572331

📂 Loading: 서울시 역사마스터 정보.csv
shape: (783, 5)

   역사_ID 역사명          호선        위도         경도
0   9010  동탄  수도권 광역급행철도  37.20034  127.09569
1   9009  구성  수도권 광역급행철도  37.29913  127.10389
2   9008  성남  수도권 광역급행철도  37.39467  127.12058
3   9007  수서  수도권 광역급행철도  37.48637  127.10161
4   9006  삼성  수도권 광역급행철도  37.50887  127.06324

📂 Loading: 서울시 병의원 위치 정보.csv
shape: (22156, 34)

,기관ID,주소,병원분류,병원분류명,응급의료기관코드,응급의료기관코드명,응급실운영여부(1/2),비고,기관설명상세,간이약도,...,진료시간(목요일)S,진료시간(금요일)S,진료시간(토요일)S,진료시간(일요일)S,진료시간(공휴일)S,우편번호1,우편번호2,병원경도,병원위도,작업시간
0,A1120837,"서울특별시 금천구 벚꽃로 286, 삼성리더스타워 111~114호 (가산동)",C,의원,G099,응급의료기관 이외,2,"외과: 상시진료, 내과는 당분간 휴진","서울시 송파구 문정동 장지동 법조단지 위례 가락동 가락시장역 위치, 삼성서울병원 외...",방이역 1번출구 바로옆 굿모닝 신한증권 뒷건물,...,900,900,900.0,1000.0,1000.0,85,11,126.884122,37.480394,2022-04-07 14:55:00.0
1,A1104130,"서울특별시 강남구 도산대로 118 (논현동, 신사빌딩 2층)",C,의원,G099,응급의료기관 이외,2,비만클리닉,"365일 진료, 국민건강보험공단 검진 지정병원 점심시간 13~14시",신사역 1번 출구 인근,...,1100,1100,1100.0,900.0,900.0,60,38,127.021809,37.516604,2021-06-07 14:54:49.0
2,A1103173,"서울특별시 강서구 화곡로68길 102, 서울시니어스가양타워 101,지103회외층 1...",C,의원,G099,응급의료기관 이외,2,휴게시간 12:30-13:30,건강검진센터,증미역 4번 출구 서울시니어스가양타워,...,900,900,900.0,900.0,900.0,75,50,126.859332,37.556989,2026-03-07 14:53:07.0
3,A1121026,"서울특별시 은평구 연서로 252, 세종빌딩 2층 (불광동)",C,의원,G099,응급의료기관 이외,2,휴게시간 13:00-14:00(토요일 제외),상처소독/ 간단한 외상처치,사가정역 2번 출구 맞은편,...,900,900,900.0,900.0,900.0,33,50,126.922920,37.619458,2026-03-07 14:53:07.0
4,A1117873,"서울특별시 관악구 신원로 38, 5층 (신림동, 청암빌딩)",N,치과의원,G099,응급의료기관 이외,2,대표번호1 지역번호 추가20170118150453,"서울시 송파구 문정동 장지동 법조단지 위례 가락동 가락시장역 위치, 삼성서울병원 외...",서월치안센터 인근 청암빌딩 5층,...,1400,1000,1000.0,1000.0,1000.0,87,76,126.929377,37.481918,2022-01-07 14:54:55.0

📂 Loading: 서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv
shape: (79871, 52)

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202602,1호선,동대문,551,14,8239,1549,7026,4980,11068,...,9385,849,2542,4,228,0,0,0,0,20260303
1,202602,1호선,동묘앞,134,2,2367,768,3345,4542,6782,...,3750,134,1811,0,240,0,0,0,0,20260303
2,202602,1호선,서울역,546,42,8614,8795,27282,49533,83751,...,28114,3893,6535,22,170,0,0,0,0,20260303
3,202602,1호선,시청,99,3,1328,4391,3042,23116,6204,...,2861,489,810,3,13,0,0,0,0,20260303
4,202602,1호선,신설동,356,3,6593,1719,8187,6967,17761,...,7449,357,2097,0,0,0,0,0,0,20260303

In [ ]:
import os
import re
import unicodedata
import numpy as np
import pandas as pd

In [ ]:
def normalize_text(s):
    return unicodedata.normalize("NFC", str(s)).strip()

def find_file_by_keyword(file_list, keyword):
    keyword = normalize_text(keyword)
    for f in file_list:
        if keyword in normalize_text(f):
            return f
    raise FileNotFoundError(f"'{keyword}' 포함 파일을 찾지 못했습니다.")

In [ ]:
subway_station_file = find_file_by_keyword(files, "지하철호선별_역별_승하차_인원")
shelter_file       = find_file_by_keyword(files, "지진대피소")
store_file         = find_file_by_keyword(files, "상가(상권)정보")
station_master_file= find_file_by_keyword(files, "역사마스터")
hospital_file      = find_file_by_keyword(files, "병의원 위치 정보")
subway_time_file   = find_file_by_keyword(files, "지하철 호선별 역별 시간대별 승하차")

In [ ]:
print(subway_station_file)
print(shelter_file)
print(store_file)
print(station_master_file)
print(hospital_file)
print(subway_time_file)

서울시_지하철호선별_역별_승하차_인원_정보.csv
서울시_지진대피소_현황.csv
소상공인시장진흥공단_상가(상권)정보_서울_202512.csv
서울시 역사마스터 정보.csv
서울시 병의원 위치 정보.csv
서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv

In [ ]:
subway_station_raw = data_dict[subway_station_file].copy()
shelter_raw        = data_dict[shelter_file].copy()
store_raw          = data_dict[store_file].copy()
station_master_raw = data_dict[station_master_file].copy()
hospital_raw       = data_dict[hospital_file].copy()
subway_time_raw    = data_dict[subway_time_file].copy()

In [ ]:
# 1번 데이터 :역별 승하차 정보에서 호선/역명만 남기기
subway_station = subway_station_raw[['호선명', '역명']].copy()
subway_station = subway_station.drop_duplicates().reset_index(drop=True)

print(subway_station.shape)
display(subway_station.head())

(621, 2)

     호선명        역명
0  우이신설선  4.19민주묘지
1    경원선        가능
2    8호선      가락시장
3    3호선      가락시장
4    7호선   가산디지털단지

In [ ]:
# 2번 파일 : 지진대피소에서 필요한 컬럼만 가져오기
shelter = shelter_raw[['시설명', '구분명', '시설면적', '경도', '위도']].copy()

shelter['시설면적'] = pd.to_numeric(shelter['시설면적'], errors='coerce')
shelter['경도'] = pd.to_numeric(shelter['경도'], errors='coerce')
shelter['위도'] = pd.to_numeric(shelter['위도'], errors='coerce')

print(shelter.shape)
display(shelter.head())

(1551, 5)

          시설명      구분명    시설면적        경도       위도
0  동작고등학교 운동장  지진실내구호소  3246.0  126.9655  37.4820
1  동작초등학교 운동장  지진실내구호소  2763.0  126.9768  37.4940
2  창림초등학교 운동장  지진실내구호소  2584.0  127.0417  37.6431
3  창원초등학교 운동장  지진실내구호소  2704.0  127.0407  37.6521
4   창일중학교 운동장  지진실내구호소  4800.0  127.0471  37.6484

In [ ]:
# 3번 파일 : 상권정보에서 필요한 컬럼만 가져오기
store = store_raw[
    ['상호명', '상권업종대분류명', '상권업종중분류명', '상권업종소분류명', '도로명주소', '경도', '위도']
].copy()

store['경도'] = pd.to_numeric(store['경도'], errors='coerce')
store['위도'] = pd.to_numeric(store['위도'], errors='coerce')

print(store.shape)
display(store.head())

(534978, 7)

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,도로명주소,경도,위도
0,60계치킨암사,음식,기타 간이,치킨,서울특별시 강동구 상암로3길 8,127.126859,37.550810
1,성심인력공사,시설관리·임대,고용 알선,고용 알선업,서울특별시 용산구 한강대로 385,126.972240,37.552803
2,칸토빈,음식,비알코올,카페,서울특별시 강서구 방화동로 30,126.810493,37.563548
3,까치노래연습장,예술·스포츠,유원지·오락,노래방,서울특별시 노원구 한글비석로23길 2,127.071218,37.660715
4,금빛주얼리,소매,시계·귀금속 소매,시계/귀금속 소매업,서울특별시 종로구 돈화문로10길 2,126.991861,37.572331

In [ ]:
# 4번 파일 : 역사마스터 정보 가져오기
station_master = station_master_raw[['역사명', '호선', '위도', '경도']].copy()

station_master['위도'] = pd.to_numeric(station_master['위도'], errors='coerce')
station_master['경도'] = pd.to_numeric(station_master['경도'], errors='coerce')

print(station_master.shape)
display(station_master.head())

(783, 4)

  역사명          호선        위도         경도
0  동탄  수도권 광역급행철도  37.20034  127.09569
1  구성  수도권 광역급행철도  37.29913  127.10389
2  성남  수도권 광역급행철도  37.39467  127.12058
3  수서  수도권 광역급행철도  37.48637  127.10161
4  삼성  수도권 광역급행철도  37.50887  127.06324

In [ ]:
# 5번 파일 : 병의원 위치 정보 가져오기
hospital_time_cols = [c for c in hospital_raw.columns if '진료시간' in c]

hospital_keep_cols = ['기관ID', '병원분류명', '응급실운영여부(1/2)', '병원경도', '병원위도'] + hospital_time_cols
hospital_keep_cols = [c for c in hospital_keep_cols if c in hospital_raw.columns]

hospital = hospital_raw[hospital_keep_cols].copy()

hospital['병원경도'] = pd.to_numeric(hospital['병원경도'], errors='coerce')
hospital['병원위도'] = pd.to_numeric(hospital['병원위도'], errors='coerce')

print(hospital.shape)
display(hospital.head())

(22156, 21)

,기관ID,병원분류명,응급실운영여부(1/2),병원경도,병원위도,진료시간(월요일)C,진료시간(화요일)C,진료시간(수요일)C,진료시간(목요일)C,진료시간(금요일)C,...,진료시간(일요일)C,진료시간(공휴일)C,진료시간(월요일)S,진료시간(화요일)S,진료시간(수요일)S,진료시간(목요일)S,진료시간(금요일)S,진료시간(토요일)S,진료시간(일요일)S,진료시간(공휴일)S
0,A1120837,의원,2,126.884122,37.480394,1930,1930,1930,1930,1930,...,1500.0,1500.0,900,900,900,900,900,900.0,1000.0,1000.0
1,A1104130,의원,2,127.021809,37.516604,2000,2000,1900,2000,2000,...,1400.0,1400.0,1100,1100,1100,1100,1100,1100.0,900.0,900.0
2,A1103173,의원,2,126.859332,37.556989,1700,1700,1700,1700,1700,...,1300.0,1630.0,900,900,900,900,900,900.0,900.0,900.0
3,A1121026,의원,2,126.922920,37.619458,2000,2000,2000,2000,2000,...,1400.0,2400.0,900,900,900,900,900,900.0,900.0,900.0
4,A1117873,치과의원,2,126.929377,37.481918,1900,2100,1900,2100,1900,...,1500.0,1500.0,1000,1000,930,1400,1000,1000.0,1000.0,1000.0

In [ ]:
# 시간대별 승하차 정보 + 역사마스터 결합
station_master_merge = station_master.rename(columns={
    '역사명': 'station_name',
    '호선': 'line_name',
    '위도': 'lat',
    '경도': 'lon'
}).copy()

subway_time = subway_time_raw.copy()
subway_time = subway_time.rename(columns={
    '지하철역': 'station_name',
    '호선명': 'line_name'
})

In [ ]:
def clean_station_text(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = re.sub(r'\s+', '', x)
    return x

station_master_merge['station_name'] = station_master_merge['station_name'].apply(clean_station_text)
station_master_merge['line_name'] = station_master_merge['line_name'].apply(clean_station_text)

subway_time['station_name'] = subway_time['station_name'].apply(clean_station_text)
subway_time['line_name'] = subway_time['line_name'].apply(clean_station_text)

In [ ]:
subway_time_merged = subway_time.merge(
    station_master_merge,
    on=['station_name', 'line_name'],
    how='left'
)

print(subway_time_merged.shape)
display(subway_time_merged.head())

(79871, 54)

,사용월,line_name,station_name,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자,lat,lon
0,202602,1호선,동대문,551,14,8239,1549,7026,4980,11068,...,2542,4,228,0,0,0,0,20260303,37.571687,127.010930
1,202602,1호선,동묘앞,134,2,2367,768,3345,4542,6782,...,1811,0,240,0,0,0,0,20260303,37.573197,127.016480
2,202602,1호선,서울역,546,42,8614,8795,27282,49533,83751,...,6535,22,170,0,0,0,0,20260303,37.556228,126.972135
3,202602,1호선,시청,99,3,1328,4391,3042,23116,6204,...,810,3,13,0,0,0,0,20260303,37.565715,126.977088
4,202602,1호선,신설동,356,3,6593,1719,8187,6967,17761,...,2097,0,0,0,0,0,0,20260303,37.576048,127.024634

In [ ]:
unmatched_subway = subway_time_merged['lat'].isna().sum()
print("시간대별 승하차 데이터에서 위경도 매핑 안 된 행 수:", unmatched_subway)

display(
    subway_time_merged[subway_time_merged['lat'].isna()][['line_name', 'station_name']].drop_duplicates().head(20)
)

시간대별 승하차 데이터에서 위경도 매핑 안 된 행 수: 7593

    line_name    station_name
16        2호선        낙성대(강감찬)
20        2호선  동대문역사문화공원(DDP)
98        4호선  동대문역사문화공원(DDP)
105       4호선      삼각지(전쟁기념관)
135       5호선  동대문역사문화공원(DDP)
172       5호선     하남시청(덕풍?신장)
192       6호선      삼각지(전쟁기념관)
237       7호선              상봉
244       7호선     용마산(용마폭포공원)
246       7호선      자양(뚝섬한강공원)
289       9호선     마곡나루(서울식물원)
302  9호선2~3단계            둔촌오륜
303  9호선2~3단계             봉은사
304  9호선2~3단계            삼성중앙
305  9호선2~3단계              삼전
306  9호선2~3단계              석촌
307  9호선2~3단계            석촌고분
308  9호선2~3단계             선정릉
309  9호선2~3단계            송파나루
310  9호선2~3단계              언주

In [ ]:
# 좌표 컬럼명 통일
shelter = shelter.rename(columns={'위도': 'lat', '경도': 'lon'})
store = store.rename(columns={'위도': 'lat', '경도': 'lon'})
hospital = hospital.rename(columns={'병원위도': 'lat', '병원경도': 'lon'})

In [ ]:
def filter_valid_seoul_coords(df, lat_col='lat', lon_col='lon'):
    out = df.copy()
    out[lat_col] = pd.to_numeric(out[lat_col], errors='coerce')
    out[lon_col] = pd.to_numeric(out[lon_col], errors='coerce')

    before = len(out)

    out = out.dropna(subset=[lat_col, lon_col])
    out = out[
        (out[lat_col].between(37.40, 37.72)) &
        (out[lon_col].between(126.75, 127.20))
    ].copy()

    after = len(out)
    print(f"removed invalid coord rows: {before - after}")
    return out

shelter = filter_valid_seoul_coords(shelter)
store = filter_valid_seoul_coords(store)
hospital = filter_valid_seoul_coords(hospital)
station_master_merge = filter_valid_seoul_coords(station_master_merge)
subway_time_merged = filter_valid_seoul_coords(subway_time_merged)

removed invalid coord rows: 0
removed invalid coord rows: 0
removed invalid coord rows: 0
removed invalid coord rows: 294
removed invalid coord rows: 27567

In [ ]:
# 위경도 격자 키 만들기
from pyproj import Transformer

transformer = Transformer.from_crs("EPSG:4326", "EPSG:5179", always_xy=True)

def add_grid_key(df, lon_col='lon', lat_col='lat', grid_size=500):
    out = df.copy()

    x, y = transformer.transform(out[lon_col].values, out[lat_col].values)
    out['x_m'] = x
    out['y_m'] = y

    out['grid_x'] = np.floor(out['x_m'] / grid_size).astype('Int64')
    out['grid_y'] = np.floor(out['y_m'] / grid_size).astype('Int64')
    out['grid_id'] = out['grid_x'].astype(str) + "_" + out['grid_y'].astype(str)

    return out

In [ ]:
GRID_SIZE = 500  # 필요하면 250, 1000으로 바꿔도 됨

shelter_g = add_grid_key(shelter, grid_size=GRID_SIZE)
store_g = add_grid_key(store, grid_size=GRID_SIZE)
hospital_g = add_grid_key(hospital, grid_size=GRID_SIZE)
station_master_g = add_grid_key(station_master_merge, grid_size=GRID_SIZE)
subway_time_g = add_grid_key(subway_time_merged, grid_size=GRID_SIZE)

In [ ]:
def check_grid_mapping(df, name):
    missing = df['grid_id'].isna().sum()
    print(f"{name}: total={len(df)}, grid_id missing={missing}")

check_grid_mapping(shelter_g, "shelter")
check_grid_mapping(store_g, "store")
check_grid_mapping(hospital_g, "hospital")
check_grid_mapping(station_master_g, "station_master")
check_grid_mapping(subway_time_g, "subway_time")

shelter: total=1551, grid_id missing=0
store: total=534978, grid_id missing=0
hospital: total=22156, grid_id missing=0
station_master: total=489, grid_id missing=0
subway_time: total=52304, grid_id missing=0

In [ ]:
# 매핑 안된 행 제거하기
shelter_g = shelter_g.dropna(subset=['grid_id']).copy()
store_g = store_g.dropna(subset=['grid_id']).copy()
hospital_g = hospital_g.dropna(subset=['grid_id']).copy()
station_master_g = station_master_g.dropna(subset=['grid_id']).copy()
subway_time_g = subway_time_g.dropna(subset=['grid_id']).copy()

In [ ]:
display(shelter_g.head())
display(store_g.head())
display(hospital_g.head())
display(station_master_g.head())
display(subway_time_g.head())

,시설명,구분명,시설면적,lon,lat,x_m,y_m,grid_x,grid_y,grid_id
0,동작고등학교 운동장,지진실내구호소,3246.0,126.9655,37.4820,952743.987376,1.942663e+06,1905,3885,1905_3885
1,동작초등학교 운동장,지진실내구호소,2763.0,126.9768,37.4940,953750.445014,1.943989e+06,1907,3887,1907_3887
2,창림초등학교 운동장,지진실내구호소,2584.0,127.0417,37.6431,959568.150999,1.960501e+06,1919,3921,1919_3921
3,창원초등학교 운동장,지진실내구호소,2704.0,127.0407,37.6521,959484.818380,1.961500e+06,1918,3923,1918_3923
4,창일중학교 운동장,지진실내구호소,4800.0,127.0471,37.6484,960047.387869,1.961087e+06,1920,3922,1920_3922

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,도로명주소,lon,lat,x_m,y_m,grid_x,grid_y,grid_id
0,60계치킨암사,음식,기타 간이,치킨,서울특별시 강동구 상암로3길 8,127.126859,37.550810,967040.379978,1.950229e+06,1934,3900,1934_3900
1,성심인력공사,시설관리·임대,고용 알선,고용 알선업,서울특별시 용산구 한강대로 385,126.972240,37.552803,953383.912950,1.950515e+06,1906,3901,1906_3901
2,칸토빈,음식,비알코올,카페,서울특별시 강서구 방화동로 30,126.810493,37.563548,939105.767716,1.951800e+06,1878,3903,1878_3903
3,까치노래연습장,예술·스포츠,유원지·오락,노래방,서울특별시 노원구 한글비석로23길 2,127.071218,37.660715,962181.254422,1.962443e+06,1924,3924,1924_3924
4,금빛주얼리,소매,시계·귀금속 소매,시계/귀금속 소매업,서울특별시 종로구 돈화문로10길 2,126.991861,37.572331,955128.763742,1.952672e+06,1910,3905,1910_3905

,기관ID,병원분류명,응급실운영여부(1/2),lon,lat,진료시간(월요일)C,진료시간(화요일)C,진료시간(수요일)C,진료시간(목요일)C,진료시간(금요일)C,...,진료시간(목요일)S,진료시간(금요일)S,진료시간(토요일)S,진료시간(일요일)S,진료시간(공휴일)S,x_m,y_m,grid_x,grid_y,grid_id
0,A1120837,의원,2,126.884122,37.480394,1930,1930,1930,1930,1930,...,900,900,900.0,1000.0,1000.0,945548.036811,1.942529e+06,1891,3885,1891_3885
1,A1104130,의원,2,127.021809,37.516604,2000,2000,1900,2000,2000,...,1100,1100,1100.0,900.0,900.0,957741.851793,1.946476e+06,1915,3892,1915_3892
2,A1103173,의원,2,126.859332,37.556989,1700,1700,1700,1700,1700,...,900,900,900.0,900.0,900.0,943414.031679,1.951042e+06,1886,3902,1886_3902
3,A1121026,의원,2,126.922920,37.619458,2000,2000,2000,2000,2000,...,900,900,900.0,900.0,900.0,949073.025833,1.957936e+06,1898,3915,1898_3915
4,A1117873,치과의원,2,126.929377,37.481918,1900,2100,1900,2100,1900,...,1400,1000,1000.0,1000.0,1000.0,949550.188500,1.942673e+06,1899,3885,1899_3885

,station_name,line_name,lat,lon,x_m,y_m,grid_x,grid_y,grid_id
3,수서,수도권광역급행철도,37.48637,127.10161,964779.804395,1.943089e+06,1929,3886,1929_3886
4,삼성,수도권광역급행철도,37.50887,127.06324,961399.220682,1.945600e+06,1922,3891,1922_3891
5,서울,수도권광역급행철도,37.55569,126.97296,953449.344498,1.950835e+06,1906,3901,1906_3901
6,연신내,수도권광역급행철도,37.61878,126.92130,948929.576000,1.957862e+06,1897,3915,1897_3915
7,대곡,수도권광역급행철도,37.63191,126.81113,939217.627156,1.959384e+06,1878,3918,1878_3918

,사용월,line_name,station_name,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,03시-04시 승차인원,03시-04시 하차인원,작업일자,lat,lon,x_m,y_m,grid_x,grid_y,grid_id
0,202602,1호선,동대문,551,14,8239,1549,7026,4980,11068,...,0,0,20260303,37.571687,127.010930,956812.291651,1.952592e+06,1913,3905,1913_3905
1,202602,1호선,동묘앞,134,2,2367,768,3345,4542,6782,...,0,0,20260303,37.573197,127.016480,957303.253849,1.952757e+06,1914,3905,1914_3905
2,202602,1호선,서울역,546,42,8614,8795,27282,49533,83751,...,0,0,20260303,37.556228,126.972135,953376.811275,1.950895e+06,1906,3901,1906_3901
3,202602,1호선,시청,99,3,1328,4391,3042,23116,6204,...,0,0,20260303,37.565715,126.977088,953820.139627,1.951945e+06,1907,3903,1907_3903
4,202602,1호선,신설동,356,3,6593,1719,8187,6967,17761,...,0,0,20260303,37.576048,127.024634,958024.889224,1.953070e+06,1916,3906,1916_3906

In [ ]:
save_path = os.path.join(base_path, "processed")
os.makedirs(save_path, exist_ok=True)

shelter_g.to_csv(os.path.join(save_path, "shelter_processed.csv"), index=False, encoding='utf-8-sig')
store_g.to_csv(os.path.join(save_path, "store_processed.csv"), index=False, encoding='utf-8-sig')
hospital_g.to_csv(os.path.join(save_path, "hospital_processed.csv"), index=False, encoding='utf-8-sig')
station_master_g.to_csv(os.path.join(save_path, "station_master_processed.csv"), index=False, encoding='utf-8-sig')
subway_time_g.to_csv(os.path.join(save_path, "subway_time_processed.csv"), index=False, encoding='utf-8-sig')

In [ ]:
#지하철 역 부분만 다시 수정하기
import re
import numpy as np
import pandas as pd

def clean_station_name(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = re.sub(r'\s+', '', x)          # 공백 제거
    x = re.sub(r'\(.*?\)', '', x)      # 괄호 내용 제거
    return x

def clean_line_name(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = re.sub(r'\s+', '', x)

    # 자주 나오는 호선명 표준화
    line_map = {
        '9호선2~3단계': '9호선',
        '9호선2단계': '9호선',
        '9호선3단계': '9호선',
    }
    return line_map.get(x, x)

# 복사
station_master_merge2 = station_master_raw[['역사명', '호선', '위도', '경도']].copy()
station_master_merge2 = station_master_merge2.rename(columns={
    '역사명': 'station_name',
    '호선': 'line_name',
    '위도': 'lat',
    '경도': 'lon'
})

subway_time2 = subway_time_raw.copy().rename(columns={
    '지하철역': 'station_name',
    '호선명': 'line_name'
})

# 정제 컬럼 생성
station_master_merge2['station_name_clean'] = station_master_merge2['station_name'].apply(clean_station_name)
station_master_merge2['line_name_clean'] = station_master_merge2['line_name'].apply(clean_line_name)

subway_time2['station_name_clean'] = subway_time2['station_name'].apply(clean_station_name)
subway_time2['line_name_clean'] = subway_time2['line_name'].apply(clean_line_name)

# merge
subway_time_merged2 = subway_time2.merge(
    station_master_merge2[['station_name_clean', 'line_name_clean', 'lat', 'lon']],
    on=['station_name_clean', 'line_name_clean'],
    how='left'
)

# 결과 확인
unmatched_after = subway_time_merged2['lat'].isna().sum()
print("정제 후 위경도 매핑 안 된 행 수:", unmatched_after)
print("전체 행 수:", len(subway_time_merged2))
print("매핑 성공률:", round((1 - unmatched_after / len(subway_time_merged2)) * 100, 2), "%")

display(
    subway_time_merged2[subway_time_merged2['lat'].isna()][['line_name', 'station_name']]
    .drop_duplicates()
    .sort_values(['line_name', 'station_name'])
    .head(30)
)

정제 후 위경도 매핑 안 된 행 수: 5695
전체 행 수: 79871
매핑 성공률: 92.87 %

      line_name station_name
67119       2호선           신천
6932        4호선          당고개
246         7호선   자양(뚝섬한강공원)
302    9호선2~3단계         둔촌오륜
303    9호선2~3단계          봉은사
304    9호선2~3단계         삼성중앙
305    9호선2~3단계           삼전
306    9호선2~3단계           석촌
307    9호선2~3단계         석촌고분
308    9호선2~3단계          선정릉
309    9호선2~3단계         송파나루
310    9호선2~3단계           언주
311    9호선2~3단계  올림픽공원(한국체대)
312    9호선2~3단계        종합운동장
313    9호선2~3단계       중앙보훈병원
314    9호선2~3단계         한성백제
53440    9호선2단계          봉은사
53441    9호선2단계         삼성중앙
53442    9호선2단계          선정릉
53443    9호선2단계           언주
53444    9호선2단계        종합운동장
364         경부선         평택지제
394         경원선           창동
16542       경원선          초성리
399         경의선           가좌
400         경의선           강매
401         경의선           검암
402         경의선           계양
403         경의선           곡산
404         경의선           공덕

In [ ]:
print("전체 행 수:", len(subway_time_merged2))
print("고유 역명 수:", subway_time_merged2['station_name'].nunique())
print("고유 호선-역 조합 수:", subway_time_merged2[['line_name', 'station_name']].drop_duplicates().shape[0])
print("고유 사용월 수:", subway_time_merged2['사용월'].nunique())

전체 행 수: 79871
고유 역명 수: 600
고유 호선-역 조합 수: 713
고유 사용월 수: 134

In [ ]:
subway_time_merged2.head(10)

,사용월,line_name,station_name,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자,station_name_clean,line_name_clean,lat,lon
0,202602,1호선,동대문,551,14,8239,1549,7026,4980,11068,...,228,0,0,0,0,20260303,동대문,1호선,37.571687,127.010930
1,202602,1호선,동묘앞,134,2,2367,768,3345,4542,6782,...,240,0,0,0,0,20260303,동묘앞,1호선,37.573197,127.016480
2,202602,1호선,서울역,546,42,8614,8795,27282,49533,83751,...,170,0,0,0,0,20260303,서울역,1호선,37.556228,126.972135
3,202602,1호선,시청,99,3,1328,4391,3042,23116,6204,...,13,0,0,0,0,20260303,시청,1호선,37.565715,126.977088
4,202602,1호선,신설동,356,3,6593,1719,8187,6967,17761,...,0,0,0,0,0,20260303,신설동,1호선,37.576048,127.024634
5,202602,1호선,제기동,269,3,4135,2266,7045,7831,16927,...,0,0,0,0,0,20260303,제기동,1호선,37.578103,127.034893
6,202602,1호선,종각,85,0,3271,5127,3794,30009,5573,...,2,0,0,0,0,20260303,종각,1호선,37.570161,126.982923
7,202602,1호선,종로3가,104,9,2907,3155,3544,11581,5873,...,35,0,0,0,0,20260303,종로3가,1호선,37.570406,126.991847
8,202602,1호선,종로5가,44,0,1427,3632,2491,14565,4854,...,2,0,0,0,0,20260303,종로5가,1호선,37.570926,127.001849
9,202602,1호선,청량리(서울시립대입구),973,30,8635,2299,14436,9225,40455,...,4,0,0,0,0,20260303,청량리,1호선,37.579956,127.044585

In [ ]:
# 시간대별로 압축
time_cols = subway_time_merged2.columns

def sum_time_range(df, start, end, prefix='승차인원'):
    cols = [c for c in df.columns if prefix in c and any(f"{h:02d}시" in c for h in range(start, end))]
    return df[cols].sum(axis=1)

subway_time_feat = subway_time_merged2.copy()

# 출근
subway_time_feat['commute_in'] = sum_time_range(subway_time_feat, 7, 10, '승차인원')
subway_time_feat['commute_out'] = sum_time_range(subway_time_feat, 7, 10, '하차인원')

# 낮
subway_time_feat['day_in'] = sum_time_range(subway_time_feat, 10, 17, '승차인원')
subway_time_feat['day_out'] = sum_time_range(subway_time_feat, 10, 17, '하차인원')

# 퇴근
subway_time_feat['evening_in'] = sum_time_range(subway_time_feat, 17, 20, '승차인원')
subway_time_feat['evening_out'] = sum_time_range(subway_time_feat, 17, 20, '하차인원')

In [ ]:
# 겹치는 월 제거
subway_station_level = (
    subway_time_feat
    .groupby(['line_name', 'station_name', 'lat', 'lon'])
    [['commute_in','commute_out','day_in','day_out','evening_in','evening_out']]
    .mean()
    .reset_index()
)

In [ ]:
subway_station_level = add_grid_key(subway_station_level, grid_size=500)

In [ ]:
subway_grid = (
    subway_station_level
    .groupby('grid_id')
    [['commute_in','commute_out','day_in','day_out','evening_in','evening_out']]
    .sum()
    .reset_index()
)

In [ ]:
# 전처리 데이터셋 확인하기
import os
import pandas as pd

base_path = "/content/drive/MyDrive/승화 토프/processed"
files = os.listdir(base_path)

print("📂 파일 목록:")
for f in files:
    print(f)

📂 파일 목록:
shelter_processed.csv
store_processed.csv
hospital_processed.csv
station_master_processed.csv
subway_time_processed.csv

In [ ]:
data = {}

for file in files:
    if file.endswith(".csv"):
        file_path = os.path.join(base_path, file)

        print(f"\n📂 Loading: {file}")

        df = pd.read_csv(file_path, encoding='utf-8-sig')
        data[file] = df

        print("shape:", df.shape)
        display(df.head())

📂 Loading: shelter_processed.csv
shape: (1551, 10)

,시설명,구분명,시설면적,lon,lat,x_m,y_m,grid_x,grid_y,grid_id
0,동작고등학교 운동장,지진실내구호소,3246.0,126.9655,37.4820,952743.987376,1.942663e+06,1905,3885,1905_3885
1,동작초등학교 운동장,지진실내구호소,2763.0,126.9768,37.4940,953750.445014,1.943989e+06,1907,3887,1907_3887
2,창림초등학교 운동장,지진실내구호소,2584.0,127.0417,37.6431,959568.150999,1.960501e+06,1919,3921,1919_3921
3,창원초등학교 운동장,지진실내구호소,2704.0,127.0407,37.6521,959484.818380,1.961500e+06,1918,3923,1918_3923
4,창일중학교 운동장,지진실내구호소,4800.0,127.0471,37.6484,960047.387869,1.961087e+06,1920,3922,1920_3922

📂 Loading: store_processed.csv
shape: (534978, 12)

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,도로명주소,lon,lat,x_m,y_m,grid_x,grid_y,grid_id
0,60계치킨암사,음식,기타 간이,치킨,서울특별시 강동구 상암로3길 8,127.126859,37.550810,967040.379978,1.950229e+06,1934,3900,1934_3900
1,성심인력공사,시설관리·임대,고용 알선,고용 알선업,서울특별시 용산구 한강대로 385,126.972240,37.552803,953383.912950,1.950515e+06,1906,3901,1906_3901
2,칸토빈,음식,비알코올,카페,서울특별시 강서구 방화동로 30,126.810493,37.563548,939105.767716,1.951800e+06,1878,3903,1878_3903
3,까치노래연습장,예술·스포츠,유원지·오락,노래방,서울특별시 노원구 한글비석로23길 2,127.071218,37.660715,962181.254422,1.962443e+06,1924,3924,1924_3924
4,금빛주얼리,소매,시계·귀금속 소매,시계/귀금속 소매업,서울특별시 종로구 돈화문로10길 2,126.991861,37.572331,955128.763742,1.952672e+06,1910,3905,1910_3905

📂 Loading: hospital_processed.csv
shape: (22156, 26)

,기관ID,병원분류명,응급실운영여부(1/2),lon,lat,진료시간(월요일)C,진료시간(화요일)C,진료시간(수요일)C,진료시간(목요일)C,진료시간(금요일)C,...,진료시간(목요일)S,진료시간(금요일)S,진료시간(토요일)S,진료시간(일요일)S,진료시간(공휴일)S,x_m,y_m,grid_x,grid_y,grid_id
0,A1120837,의원,2,126.884122,37.480394,1930,1930,1930,1930,1930,...,900,900,900.0,1000.0,1000.0,945548.036811,1.942529e+06,1891,3885,1891_3885
1,A1104130,의원,2,127.021809,37.516604,2000,2000,1900,2000,2000,...,1100,1100,1100.0,900.0,900.0,957741.851793,1.946476e+06,1915,3892,1915_3892
2,A1103173,의원,2,126.859332,37.556989,1700,1700,1700,1700,1700,...,900,900,900.0,900.0,900.0,943414.031679,1.951042e+06,1886,3902,1886_3902
3,A1121026,의원,2,126.922920,37.619458,2000,2000,2000,2000,2000,...,900,900,900.0,900.0,900.0,949073.025833,1.957936e+06,1898,3915,1898_3915
4,A1117873,치과의원,2,126.929377,37.481918,1900,2100,1900,2100,1900,...,1400,1000,1000.0,1000.0,1000.0,949550.188500,1.942673e+06,1899,3885,1899_3885

📂 Loading: station_master_processed.csv
shape: (489, 9)

,station_name,line_name,lat,lon,x_m,y_m,grid_x,grid_y,grid_id
0,수서,수도권광역급행철도,37.48637,127.10161,964779.804395,1.943089e+06,1929,3886,1929_3886
1,삼성,수도권광역급행철도,37.50887,127.06324,961399.220682,1.945600e+06,1922,3891,1922_3891
2,서울,수도권광역급행철도,37.55569,126.97296,953449.344498,1.950835e+06,1906,3901,1906_3901
3,연신내,수도권광역급행철도,37.61878,126.92130,948929.576000,1.957862e+06,1897,3915,1897_3915
4,대곡,수도권광역급행철도,37.63191,126.81113,939217.627156,1.959384e+06,1878,3918,1878_3918

📂 Loading: subway_time_processed.csv
shape: (52304, 59)

,사용월,line_name,station_name,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,03시-04시 승차인원,03시-04시 하차인원,작업일자,lat,lon,x_m,y_m,grid_x,grid_y,grid_id
0,202602,1호선,동대문,551,14,8239,1549,7026,4980,11068,...,0,0,20260303,37.571687,127.010930,956812.291651,1.952592e+06,1913,3905,1913_3905
1,202602,1호선,동묘앞,134,2,2367,768,3345,4542,6782,...,0,0,20260303,37.573197,127.016480,957303.253849,1.952757e+06,1914,3905,1914_3905
2,202602,1호선,서울역,546,42,8614,8795,27282,49533,83751,...,0,0,20260303,37.556228,126.972135,953376.811275,1.950895e+06,1906,3901,1906_3901
3,202602,1호선,시청,99,3,1328,4391,3042,23116,6204,...,0,0,20260303,37.565715,126.977088,953820.139627,1.951945e+06,1907,3903,1907_3903
4,202602,1호선,신설동,356,3,6593,1719,8187,6967,17761,...,0,0,20260303,37.576048,127.024634,958024.889224,1.953070e+06,1916,3906,1916_3906

In [ ]:
import os

processed_path = "/content/drive/MyDrive/승화 토프/processed"
os.makedirs(processed_path, exist_ok=True)

# subway_time_merged2를 최종 저장용으로 사용
subway_time_final = subway_time_merged2.copy()

# 좌표 유효 범위 다시 한 번 필터
subway_time_final = subway_time_final.dropna(subset=['lat', 'lon']).copy()
subway_time_final = subway_time_final[
    (subway_time_final['lat'].between(37.40, 37.72)) &
    (subway_time_final['lon'].between(126.75, 127.20))
].copy()

# 혹시 아직 grid_id 없으면 다시 생성
if 'grid_id' not in subway_time_final.columns:
    from pyproj import Transformer
    import numpy as np

    transformer = Transformer.from_crs("EPSG:4326", "EPSG:5179", always_xy=True)

    x, y = transformer.transform(subway_time_final['lon'].values, subway_time_final['lat'].values)
    subway_time_final['x_m'] = x
    subway_time_final['y_m'] = y

    GRID_SIZE = 500
    subway_time_final['grid_x'] = np.floor(subway_time_final['x_m'] / GRID_SIZE).astype('Int64')
    subway_time_final['grid_y'] = np.floor(subway_time_final['y_m'] / GRID_SIZE).astype('Int64')
    subway_time_final['grid_id'] = subway_time_final['grid_x'].astype(str) + "_" + subway_time_final['grid_y'].astype(str)

# 저장 (덮어쓰기)
save_file = os.path.join(processed_path, "subway_time_processed.csv")
subway_time_final.to_csv(save_file, index=False, encoding='utf-8-sig')

print("저장 완료:", save_file)
print("shape:", subway_time_final.shape)
display(subway_time_final.head())

저장 완료: /content/drive/MyDrive/승화 토프/processed/subway_time_processed.csv
shape: (54121, 61)

,사용월,line_name,station_name,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,작업일자,station_name_clean,line_name_clean,lat,lon,x_m,y_m,grid_x,grid_y,grid_id
0,202602,1호선,동대문,551,14,8239,1549,7026,4980,11068,...,20260303,동대문,1호선,37.571687,127.010930,956812.291651,1.952592e+06,1913,3905,1913_3905
1,202602,1호선,동묘앞,134,2,2367,768,3345,4542,6782,...,20260303,동묘앞,1호선,37.573197,127.016480,957303.253849,1.952757e+06,1914,3905,1914_3905
2,202602,1호선,서울역,546,42,8614,8795,27282,49533,83751,...,20260303,서울역,1호선,37.556228,126.972135,953376.811275,1.950895e+06,1906,3901,1906_3901
3,202602,1호선,시청,99,3,1328,4391,3042,23116,6204,...,20260303,시청,1호선,37.565715,126.977088,953820.139627,1.951945e+06,1907,3903,1907_3903
4,202602,1호선,신설동,356,3,6593,1719,8187,6967,17761,...,20260303,신설동,1호선,37.576048,127.024634,958024.889224,1.953070e+06,1916,3906,1916_3906

In [ ]:
check_subway = pd.read_csv("/content/drive/MyDrive/승화 토프/processed/subway_time_processed.csv", encoding="utf-8-sig")
print(check_subway.shape)
display(check_subway.head())

(54121, 61)

,사용월,line_name,station_name,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,작업일자,station_name_clean,line_name_clean,lat,lon,x_m,y_m,grid_x,grid_y,grid_id
0,202602,1호선,동대문,551,14,8239,1549,7026,4980,11068,...,20260303,동대문,1호선,37.571687,127.010930,956812.291651,1.952592e+06,1913,3905,1913_3905
1,202602,1호선,동묘앞,134,2,2367,768,3345,4542,6782,...,20260303,동묘앞,1호선,37.573197,127.016480,957303.253849,1.952757e+06,1914,3905,1914_3905
2,202602,1호선,서울역,546,42,8614,8795,27282,49533,83751,...,20260303,서울역,1호선,37.556228,126.972135,953376.811275,1.950895e+06,1906,3901,1906_3901
3,202602,1호선,시청,99,3,1328,4391,3042,23116,6204,...,20260303,시청,1호선,37.565715,126.977088,953820.139627,1.951945e+06,1907,3903,1907_3903
4,202602,1호선,신설동,356,3,6593,1719,8187,6967,17761,...,20260303,신설동,1호선,37.576048,127.024634,958024.889224,1.953070e+06,1916,3906,1916_3906

In [ ]:
import os

base_path = "/content/drive/MyDrive/승화 토프"
all_files = os.listdir(base_path)

print("📂 승화 토프 폴더 파일 목록")
for f in all_files:
    print(f)

📂 승화 토프 폴더 파일 목록
toyproj.ipynb
서울시_지하철호선별_역별_승하차_인원_정보.csv
서울시_지진대피소_현황.csv
소상공인시장진흥공단_상가(상권)정보_서울_202512.csv
기타
서울시 역사마스터 정보.csv
서울시 병의원 위치 정보.csv
서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv
processed
250m_생활인구.csv

In [ ]:
import pandas as pd
import unicodedata

def normalize_text(s):
    return unicodedata.normalize("NFC", str(s)).strip()

life_pop_files = [f for f in all_files if "250m" in normalize_text(f) and "생활인구" in normalize_text(f)]

print("찾은 파일:")
for f in life_pop_files:
    print(f)

찾은 파일:
250m_생활인구.csv

In [ ]:
import os
import pandas as pd

base_path = "/content/drive/MyDrive/승화 토프"
life_pop_file = "250m_생활인구.csv"
life_pop_path = os.path.join(base_path, life_pop_file)

# 불러오기
try:
    life_pop_df = pd.read_csv(life_pop_path, encoding="utf-8-sig")
except:
    try:
        life_pop_df = pd.read_csv(life_pop_path, encoding="cp949")
    except:
        life_pop_df = pd.read_csv(life_pop_path)

print("파일 경로:", life_pop_path)
print("shape:", life_pop_df.shape)
print("\ncolumns:")
print(life_pop_df.columns.tolist())

display(life_pop_df.head())

파일 경로: /content/drive/MyDrive/승화 토프/250m_생활인구.csv
shape: (254439, 33)

columns:
['일자', '시간', '행정동코드', '250M격자', '생활인구합계', '남자 0~9세', '남자 10~14세', '남자 15~19세', '남자 20~24세', '남자 25~29세', '남자 30~34세', '남자 35~39세', '남자 40~44세', '남자 45~49세', '남자 50~54세', '남자 55~59세', '남자 60~64세', '남자 65~69세', '남자 70세 이상', '여자 0~9세', '여자 10~14세', '여자 15~19세', '여자 20~24세', '여자 25~29세', '여자 30~34세', '여자 35~39세', '여자 40~44세', '여자 45~49세', '여자 50~54세', '여자 55~59세', '여자 60~64세', '여자 65~69세', '여자 70세 이상']

,일자,시간,행정동코드,250M격자,생활인구합계,남자 0~9세,남자 10~14세,남자 15~19세,남자 20~24세,남자 25~29세,...,여자 25~29세,여자 30~34세,여자 35~39세,여자 40~44세,여자 45~49세,여자 50~54세,여자 55~59세,여자 60~64세,여자 65~69세,여자 70세 이상
0,20260318,0,11110515,다사52255325,4.49,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
1,20260318,0,11110515,다사52255350,5.48,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
2,20260318,0,11110515,다사52255375,11.95,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
3,20260318,0,11110515,다사52505325,17.59,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
4,20260318,0,11110515,다사52505350,950.33,5.31,4.84,11.37,19.6,32.01,...,70.64,45.35,44.21,34.95,66.71,53.08,34.73,27.85,38.35,100.57

In [ ]:
import os
import re
import ast
import numpy as np
import pandas as pd

from pyproj import Transformer
from scipy.spatial import cKDTree

In [ ]:
import os
import pandas as pd

base_path = "/content/drive/MyDrive/승화 토프"
life_pop_path = os.path.join(base_path, "250m_생활인구.csv")

encodings_to_try = ["cp949", "euc-kr", "utf-8-sig", "utf-8"]

life_pop_df = None
for enc in encodings_to_try:
    try:
        life_pop_df = pd.read_csv(life_pop_path, encoding=enc)
        print(f"성공한 인코딩: {enc}")
        break
    except Exception as e:
        print(f"실패한 인코딩: {enc} | {e}")

if life_pop_df is None:
    raise ValueError("모든 인코딩으로 읽기에 실패했습니다.")

print("파일 경로:", life_pop_path)
print("shape:", life_pop_df.shape)
print("\ncolumns:")
print(life_pop_df.columns.tolist())

display(life_pop_df.head())

성공한 인코딩: cp949
파일 경로: /content/drive/MyDrive/승화 토프/250m_생활인구.csv
shape: (254439, 33)

columns:
['일자', '시간', '행정동코드', '250M격자', '생활인구합계', '남자 0~9세', '남자 10~14세', '남자 15~19세', '남자 20~24세', '남자 25~29세', '남자 30~34세', '남자 35~39세', '남자 40~44세', '남자 45~49세', '남자 50~54세', '남자 55~59세', '남자 60~64세', '남자 65~69세', '남자 70세 이상', '여자 0~9세', '여자 10~14세', '여자 15~19세', '여자 20~24세', '여자 25~29세', '여자 30~34세', '여자 35~39세', '여자 40~44세', '여자 45~49세', '여자 50~54세', '여자 55~59세', '여자 60~64세', '여자 65~69세', '여자 70세 이상']

,일자,시간,행정동코드,250M격자,생활인구합계,남자 0~9세,남자 10~14세,남자 15~19세,남자 20~24세,남자 25~29세,...,여자 25~29세,여자 30~34세,여자 35~39세,여자 40~44세,여자 45~49세,여자 50~54세,여자 55~59세,여자 60~64세,여자 65~69세,여자 70세 이상
0,20260318,0,11110515,다사52255325,4.49,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
1,20260318,0,11110515,다사52255350,5.48,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
2,20260318,0,11110515,다사52255375,11.95,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
3,20260318,0,11110515,다사52505325,17.59,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
4,20260318,0,11110515,다사52505350,950.33,5.31,4.84,11.37,19.6,32.01,...,70.64,45.35,44.21,34.95,66.71,53.08,34.73,27.85,38.35,100.57

In [ ]:
# 데이터셋 구축하기

In [ ]:
import os
import re
import numpy as np
import pandas as pd

from pyproj import Transformer
from scipy.spatial import cKDTree

base_path = "/content/drive/MyDrive/승화 토프"
processed_path = os.path.join(base_path, "processed")

# 250m 생활인구
life_pop_path = os.path.join(base_path, "250m_생활인구.csv")
life_pop_df = pd.read_csv(life_pop_path, encoding="cp949")

# processed 파일들
shelter_df = pd.read_csv(os.path.join(processed_path, "shelter_processed.csv"), encoding="utf-8-sig")
store_df = pd.read_csv(os.path.join(processed_path, "store_processed.csv"), encoding="utf-8-sig")
hospital_df = pd.read_csv(os.path.join(processed_path, "hospital_processed.csv"), encoding="utf-8-sig")
subway_df = pd.read_csv(os.path.join(processed_path, "subway_time_processed.csv"), encoding="utf-8-sig")

print("life_pop_df:", life_pop_df.shape)
print("shelter_df:", shelter_df.shape)
print("store_df:", store_df.shape)
print("hospital_df:", hospital_df.shape)
print("subway_df:", subway_df.shape)

life_pop_df: (254439, 33)
shelter_df: (1551, 10)
store_df: (534978, 12)
hospital_df: (22156, 26)
subway_df: (54121, 61)

In [ ]:
# 250m 생활인구의 격자코드만 추출
life_grid = (
    life_pop_df[['250M격자']]
    .drop_duplicates()
    .rename(columns={'250M격자': '격자코드'})
    .reset_index(drop=True)
)

print("고유 250m 격자 수:", len(life_grid))
display(life_grid.head())

고유 250m 격자 수: 8568

         격자코드
0  다사52255325
1  다사52255350
2  다사52255375
3  다사52505325
4  다사52505350

In [ ]:
# 변환기
to_lonlat = Transformer.from_crs("EPSG:5179", "EPSG:4326", always_xy=True)

def gridcode_to_xy_dasa(code: str):
    """
    서울 '다사' 격자코드를 250m 격자 중심좌표(EPSG:5179)로 변환
    예: 다사35005075 -> x=935125, y=1950875 형태
    """
    code = str(code).strip()
    if not code.startswith("다사"):
        return np.nan, np.nan

    digits = code[2:]
    if len(digits) != 8 or not digits.isdigit():
        return np.nan, np.nan

    x_part = int(digits[:4])   # 예: 3500
    y_part = int(digits[4:])   # 예: 5075

    # '다사' 100km 블록 기준 250m 격자 중심점
    # 서울 예시 코드들과 맞는 기준
    x = 900125 + x_part * 10
    y = 1900125 + y_part * 10
    return x, y

In [ ]:
# 마스터 250m 격자 좌표 생성
life_grid[['x_m', 'y_m']] = life_grid['격자코드'].apply(
    lambda x: pd.Series(gridcode_to_xy_dasa(x))
)

# lon, lat 추가
lon, lat = to_lonlat.transform(life_grid['x_m'].values, life_grid['y_m'].values)
life_grid['lon'] = lon
life_grid['lat'] = lat

print(life_grid.shape)
display(life_grid.head())

(8568, 5)

         격자코드     x_m      y_m         lon        lat
0  다사52255325  952375  1953375  126.960632  37.578526
1  다사52255350  952375  1953625  126.960616  37.580780
2  다사52255375  952375  1953875  126.960599  37.583033
3  다사52505325  952625  1953375  126.963463  37.578539
4  다사52505350  952625  1953625  126.963447  37.580792

In [ ]:
# 좌표 이상 여부 확인
print(life_grid[['lon', 'lat']].describe())
print("좌표 결측 수:")
print(life_grid[['x_m', 'y_m', 'lon', 'lat']].isnull().sum())

               lon          lat
count  8568.000000  8568.000000
mean    126.991929    37.549060
std       0.092025     0.057452
min     126.765482    37.430248
25%     126.920676    37.502121
50%     127.003003    37.546494
75%     127.064748    37.588005
max     127.181615    37.700460
좌표 결측 수:
x_m    0
y_m    0
lon    0
lat    0
dtype: int64

In [ ]:
# 점 데이터 가까운 250m 격자에 매핑하기
# 250m 마스터 KDTree
grid_tree = cKDTree(life_grid[['x_m', 'y_m']].values)

def attach_to_250m_grid(point_df, lon_col='lon', lat_col='lat', max_dist_m=180):
    """
    point_df의 점 데이터를 가장 가까운 250m 격자코드에 붙임
    max_dist_m보다 멀면 매핑 실패 처리
    """
    out = point_df.copy()

    # lon, lat -> x_m, y_m
    if 'x_m' not in out.columns or 'y_m' not in out.columns:
        tr = Transformer.from_crs("EPSG:4326", "EPSG:5179", always_xy=True)
        x, y = tr.transform(out[lon_col].values, out[lat_col].values)
        out['x_m'] = x
        out['y_m'] = y

    dists, idxs = grid_tree.query(out[['x_m', 'y_m']].values, k=1)

    out['nearest_dist_m'] = dists
    out['격자코드'] = life_grid.iloc[idxs]['격자코드'].values

    out.loc[out['nearest_dist_m'] > max_dist_m, '격자코드'] = np.nan
    return out

In [ ]:
shelter_map = attach_to_250m_grid(shelter_df, lon_col='lon', lat_col='lat', max_dist_m=180)
store_map = attach_to_250m_grid(store_df, lon_col='lon', lat_col='lat', max_dist_m=180)
hospital_map = attach_to_250m_grid(hospital_df, lon_col='lon', lat_col='lat', max_dist_m=180)
subway_map = attach_to_250m_grid(subway_df, lon_col='lon', lat_col='lat', max_dist_m=180)

print("대피소 매핑 성공률:", round(shelter_map['격자코드'].notna().mean() * 100, 2), "%")
print("상권 매핑 성공률:", round(store_map['격자코드'].notna().mean() * 100, 2), "%")
print("병원 매핑 성공률:", round(hospital_map['격자코드'].notna().mean() * 100, 2), "%")
print("지하철 매핑 성공률:", round(subway_map['격자코드'].notna().mean() * 100, 2), "%")

대피소 매핑 성공률: 99.94 %
상권 매핑 성공률: 99.99 %
병원 매핑 성공률: 100.0 %
지하철 매핑 성공률: 87.27 %

In [ ]:
# 생활인구 전처리
life_pop = life_pop_df.copy()
life_pop = life_pop.rename(columns={'250M격자': '격자코드'})

# 숫자형 변환
num_cols = [c for c in life_pop.columns if c not in ['일자', '시간', '행정동코드', '격자코드']]

for c in num_cols:
    life_pop[c] = pd.to_numeric(life_pop[c].replace('*', np.nan), errors='coerce')

life_pop['시간'] = pd.to_numeric(life_pop['시간'], errors='coerce')
life_pop['일자'] = pd.to_datetime(life_pop['일자'].astype(str), format='%Y%m%d', errors='coerce')

print(life_pop.shape)
display(life_pop.head())

(254439, 33)

,일자,시간,행정동코드,격자코드,생활인구합계,남자 0~9세,남자 10~14세,남자 15~19세,남자 20~24세,남자 25~29세,...,여자 25~29세,여자 30~34세,여자 35~39세,여자 40~44세,여자 45~49세,여자 50~54세,여자 55~59세,여자 60~64세,여자 65~69세,여자 70세 이상
0,2026-03-18,0,11110515,다사52255325,4.49,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-18,0,11110515,다사52255350,5.48,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-18,0,11110515,다사52255375,11.95,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-18,0,11110515,다사52505325,17.59,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-18,0,11110515,다사52505350,950.33,5.31,4.84,11.37,19.6,32.01,...,70.64,45.35,44.21,34.95,66.71,53.08,34.73,27.85,38.35,100.57

In [ ]:
# 1번 데이터셋 : 인구 + 시설 데이터셋
life_pop_feat = life_pop.copy()

life_pop_feat['출근시간대'] = life_pop_feat['시간'].between(7, 9)
life_pop_feat['주간시간대'] = life_pop_feat['시간'].between(10, 17)
life_pop_feat['퇴근시간대'] = life_pop_feat['시간'].between(18, 20)
life_pop_feat['야간시간대'] = ~(
    life_pop_feat['출근시간대'] |
    life_pop_feat['주간시간대'] |
    life_pop_feat['퇴근시간대']
)

pop_base = life_pop_feat.groupby('격자코드', as_index=False).agg(
    생활인구_평균=('생활인구합계', 'mean'),
    생활인구_최대=('생활인구합계', 'max'),
    생활인구_최소=('생활인구합계', 'min')
)

commute_pop = (
    life_pop_feat[life_pop_feat['출근시간대']]
    .groupby('격자코드', as_index=False)['생활인구합계']
    .mean()
    .rename(columns={'생활인구합계': '생활인구_출근시간평균'})
)

day_pop = (
    life_pop_feat[life_pop_feat['주간시간대']]
    .groupby('격자코드', as_index=False)['생활인구합계']
    .mean()
    .rename(columns={'생활인구합계': '생활인구_주간평균'})
)

evening_pop = (
    life_pop_feat[life_pop_feat['퇴근시간대']]
    .groupby('격자코드', as_index=False)['생활인구합계']
    .mean()
    .rename(columns={'생활인구합계': '생활인구_퇴근시간평균'})
)

night_pop = (
    life_pop_feat[life_pop_feat['야간시간대']]
    .groupby('격자코드', as_index=False)['생활인구합계']
    .mean()
    .rename(columns={'생활인구합계': '생활인구_야간평균'})
)

demo_cols = [c for c in life_pop_feat.columns if c.startswith('남자') or c.startswith('여자')]
demo_feat = life_pop_feat.groupby('격자코드', as_index=False)[demo_cols].mean()

population_feat = pop_base.merge(commute_pop, on='격자코드', how='left')
population_feat = population_feat.merge(day_pop, on='격자코드', how='left')
population_feat = population_feat.merge(evening_pop, on='격자코드', how='left')
population_feat = population_feat.merge(night_pop, on='격자코드', how='left')
population_feat = population_feat.merge(demo_feat, on='격자코드', how='left')

print(population_feat.shape)
display(population_feat.head())

(8568, 36)

,격자코드,생활인구_평균,생활인구_최대,생활인구_최소,생활인구_출근시간평균,생활인구_주간평균,생활인구_퇴근시간평균,생활인구_야간평균,남자 0~9세,남자 10~14세,...,여자 25~29세,여자 30~34세,여자 35~39세,여자 40~44세,여자 45~49세,여자 50~54세,여자 55~59세,여자 60~64세,여자 65~69세,여자 70세 이상
0,다사35005075,7.628235,9.56,4.22,7.010000,9.26625,7.000000,4.506667,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,다사35005100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,다사35255050,10.991250,16.46,5.52,12.113333,15.94500,12.066667,6.369000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,다사35255075,82.590833,123.59,41.42,90.863333,119.86000,90.700000,47.861000,NaN,NaN,...,6.153333,6.175,5.023,4.887,4.348889,4.888889,4.365,4.12,NaN,5.0025
4,다사35255100,42.262917,63.24,21.19,46.493333,61.32875,46.420000,24.494000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 대피소
shelter_feat = (
    shelter_map.dropna(subset=['격자코드'])
    .groupby('격자코드', as_index=False)
    .agg(
        대피소수=('시설명', 'count'),
        대피소면적합=('시설면적', 'sum'),
        대피소유형수=('구분명', 'nunique')
    )
)

# 병원
hospital_map['응급실운영여부(1/2)'] = pd.to_numeric(hospital_map['응급실운영여부(1/2)'], errors='coerce')
hospital_map['응급병원여부'] = (hospital_map['응급실운영여부(1/2)'] == 1).astype(int)

hospital_feat = (
    hospital_map.dropna(subset=['격자코드'])
    .groupby('격자코드', as_index=False)
    .agg(
        병원수=('기관ID', 'count'),
        응급병원수=('응급병원여부', 'sum'),
        병원종류수=('병원분류명', 'nunique')
    )
)

# 상권
store_feat = (
    store_map.dropna(subset=['격자코드'])
    .groupby('격자코드', as_index=False)
    .agg(
        상권수=('상호명', 'count'),
        상권대분류수=('상권업종대분류명', 'nunique'),
        상권중분류수=('상권업종중분류명', 'nunique')
    )
)

In [ ]:
population_facility_dataset = life_grid[['격자코드', 'lon', 'lat']].copy()

population_facility_dataset = population_facility_dataset.merge(population_feat, on='격자코드', how='left')
population_facility_dataset = population_facility_dataset.merge(shelter_feat, on='격자코드', how='left')
population_facility_dataset = population_facility_dataset.merge(hospital_feat, on='격자코드', how='left')
population_facility_dataset = population_facility_dataset.merge(store_feat, on='격자코드', how='left')

for c in ['대피소수', '대피소면적합', '대피소유형수',
          '병원수', '응급병원수', '병원종류수',
          '상권수', '상권대분류수', '상권중분류수']:
    if c in population_facility_dataset.columns:
        population_facility_dataset[c] = population_facility_dataset[c].fillna(0)

print("population_facility_dataset:", population_facility_dataset.shape)
display(population_facility_dataset.head())

population_facility_dataset: (8568, 47)

,격자코드,lon,lat,생활인구_평균,생활인구_최대,생활인구_최소,생활인구_출근시간평균,생활인구_주간평균,생활인구_퇴근시간평균,생활인구_야간평균,...,여자 70세 이상,대피소수,대피소면적합,대피소유형수,병원수,응급병원수,병원종류수,상권수,상권대분류수,상권중분류수
0,다사52255325,126.960632,37.578526,33.402899,68.59,4.39,32.772222,47.761250,34.806667,20.382222,...,6.244783,1.0,4953.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
1,다사52255350,126.960616,37.580780,11.575000,20.34,5.40,10.963333,18.746250,11.626667,6.006000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,다사52255375,126.960599,37.583033,25.147500,44.22,11.75,23.823333,40.720000,25.263333,13.052000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,다사52505325,126.963463,37.578539,38.253542,75.01,9.75,36.258333,65.673125,40.540000,16.230500,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,다사52505350,126.963447,37.580792,826.548333,981.45,674.67,857.263333,702.906250,752.893333,938.344000,...,92.574167,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,4.0

2번 데이터셋 : 지하철 + 노선 + 시간대별 승하차 데이터셋

In [ ]:
time_cols = [c for c in subway_map.columns if ('승차인원' in c or '하차인원' in c)]
print("시간대 컬럼 수:", len(time_cols))
print(time_cols[:10])

시간대 컬럼 수: 48
['04시-05시 승차인원', '04시-05시 하차인원', '05시-06시 승차인원', '05시-06시 하차인원', '06시-07시 승차인원', '06시-07시 하차인원', '07시-08시 승차인원', '07시-08시 하차인원', '08시-09시 승차인원', '08시-09시 하차인원']

In [ ]:
subway_station_level = (
    subway_map.dropna(subset=['격자코드'])
    .groupby(['격자코드', 'line_name', 'station_name'], as_index=False)[time_cols]
    .mean()
)

print(subway_station_level.shape)
display(subway_station_level.head())

(434, 51)

,격자코드,line_name,station_name,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 승차인원,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원
0,다사38005325,9호선,개화,7.798507,0.738806,2364.589552,242.074627,9895.925373,2660.253731,25965.731343,...,398.320896,3070.888060,108.753731,978.746269,1.656716,62.365672,0.977612,1.216418,0.052239,0.067164
1,다사38255150,5호선,김포공항,4.432836,0.559701,576.261194,2503.320896,2630.388060,8847.268657,9036.626866,...,4652.589552,1041.328358,287.119403,421.932836,1.582090,7.597015,0.029851,0.708955,0.000000,0.082090
2,다사38255150,9호선,김포공항,11.052239,0.462687,1597.141791,2279.910448,3791.723881,13384.208955,10411.813433,...,4231.283582,2758.529851,171.298507,1591.529851,1.223881,119.037313,0.044776,1.216418,0.037313,0.029851
3,다사38255150,공항철도 1호선,김포공항,18.679104,0.701493,2091.485075,1830.358209,3505.097015,10942.947761,7509.671642,...,6015.000000,1432.238806,196.701493,865.701493,1.089552,26.888060,0.223881,0.977612,0.283582,0.000000
4,다사38505150,서해선,김포공항,17.218750,4.093750,298.812500,2093.781250,638.718750,7636.031250,1640.531250,...,1912.000000,1033.875000,63.718750,351.281250,0.218750,1.375000,0.000000,0.000000,0.000000,0.000000

In [ ]:
def get_cols_by_hour_range(cols, start_hour, end_hour, keyword):
    selected = []
    for c in cols:
        if keyword not in c:
            continue
        m = re.match(r'(\d{2})시-\d{2}시', c)
        if m:
            h = int(m.group(1))
            if start_hour <= h <= end_hour:
                selected.append(c)
    return selected

ride_cols = [c for c in time_cols if '승차인원' in c]
alight_cols = [c for c in time_cols if '하차인원' in c]

commute_ride_cols = get_cols_by_hour_range(ride_cols, 7, 9, '승차인원')
commute_alight_cols = get_cols_by_hour_range(alight_cols, 7, 9, '하차인원')

day_ride_cols = get_cols_by_hour_range(ride_cols, 10, 17, '승차인원')
day_alight_cols = get_cols_by_hour_range(alight_cols, 10, 17, '하차인원')

evening_ride_cols = get_cols_by_hour_range(ride_cols, 18, 20, '승차인원')
evening_alight_cols = get_cols_by_hour_range(alight_cols, 18, 20, '하차인원')

subway_station_level['출근_승차합'] = subway_station_level[commute_ride_cols].sum(axis=1)
subway_station_level['출근_하차합'] = subway_station_level[commute_alight_cols].sum(axis=1)
subway_station_level['주간_승차합'] = subway_station_level[day_ride_cols].sum(axis=1)
subway_station_level['주간_하차합'] = subway_station_level[day_alight_cols].sum(axis=1)
subway_station_level['퇴근_승차합'] = subway_station_level[evening_ride_cols].sum(axis=1)
subway_station_level['퇴근_하차합'] = subway_station_level[evening_alight_cols].sum(axis=1)

In [ ]:
def join_unique_sorted(series):
    vals = sorted(set([str(x) for x in series.dropna().astype(str)]))
    return ", ".join(vals)

agg_dict = {c: 'sum' for c in time_cols}
agg_dict.update({
    '출근_승차합': 'sum',
    '출근_하차합': 'sum',
    '주간_승차합': 'sum',
    '주간_하차합': 'sum',
    '퇴근_승차합': 'sum',
    '퇴근_하차합': 'sum',
    'line_name': join_unique_sorted,
    'station_name': join_unique_sorted
})

subway_grid_dataset = (
    subway_station_level
    .groupby('격자코드', as_index=False)
    .agg(agg_dict)
)

station_count = (
    subway_station_level.groupby('격자코드', as_index=False)['station_name']
    .nunique()
    .rename(columns={'station_name': '지하철역수'})
)

line_count = (
    subway_station_level.groupby('격자코드', as_index=False)['line_name']
    .nunique()
    .rename(columns={'line_name': '지하철노선수'})
)

subway_grid_dataset = subway_grid_dataset.merge(station_count, on='격자코드', how='left')
subway_grid_dataset = subway_grid_dataset.merge(line_count, on='격자코드', how='left')

subway_grid_dataset = subway_grid_dataset.rename(columns={
    'line_name': '노선명목록',
    'station_name': '역사명목록'
})

subway_grid_dataset = life_grid[['격자코드', 'lon', 'lat']].merge(
    subway_grid_dataset, on='격자코드', how='right'
)

print("subway_grid_dataset:", subway_grid_dataset.shape)
display(subway_grid_dataset.head())

subway_grid_dataset: (330, 61)

,격자코드,lon,lat,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,출근_승차합,출근_하차합,주간_승차합,주간_하차합,퇴근_승차합,퇴근_하차합,노선명목록,역사명목록,지하철역수,지하철노선수
0,다사38005325,126.799256,37.577679,7.798507,0.738806,2364.589552,242.074627,9895.925373,2660.253731,25965.731343,...,53964.052239,12761.835821,42722.216418,28485.776119,14358.134328,27134.462687,9호선,개화,1,1
1,다사38255150,126.802234,37.561923,34.164179,1.723881,4264.888060,6613.589552,9927.208955,33174.425373,26958.111940,...,98439.432836,154632.388060,388797.149254,393589.388060,191177.858209,114229.776119,"5호선, 9호선, 공항철도 1호선",김포공항,1,3
2,다사38505150,126.805065,37.561940,17.218750,4.093750,298.812500,2093.781250,638.718750,7636.031250,1640.531250,...,7394.687500,29289.218750,44909.187500,67111.406250,25119.937500,13983.062500,서해선,김포공항,1,1
3,다사38505275,126.804960,37.573206,1.455224,0.119403,4099.731343,301.783582,8240.373134,4089.656716,22808.671642,...,54787.358209,29448.626866,67308.761194,57476.708955,25501.097015,41594.373134,5호선,개화산,1,1
4,다사39005150,126.810726,37.561973,17.656716,0.417910,4109.798507,1617.432836,9139.783582,5826.082090,25000.276119,...,69767.171642,32872.686567,98651.500000,87236.507463,34301.373134,59390.552239,5호선,송정,1,1

In [ ]:
final_path = os.path.join(base_path, "final_datasets")
os.makedirs(final_path, exist_ok=True)

pop_fac_path = os.path.join(final_path, "population_facility_dataset.csv")
subway_grid_path = os.path.join(final_path, "subway_grid_dataset.csv")

population_facility_dataset.to_csv(pop_fac_path, index=False, encoding='utf-8-sig')
subway_grid_dataset.to_csv(subway_grid_path, index=False, encoding='utf-8-sig')

print("저장 완료")
print(pop_fac_path)
print(subway_grid_path)

저장 완료
/content/drive/MyDrive/승화 토프/final_datasets/population_facility_dataset.csv
/content/drive/MyDrive/승화 토프/final_datasets/subway_grid_dataset.csv

In [ ]:
pop_fac_check = pd.read_csv(pop_fac_path, encoding='utf-8-sig')
subway_check = pd.read_csv(subway_grid_path, encoding='utf-8-sig')

print("population_facility_dataset:", pop_fac_check.shape)
display(pop_fac_check.head())

print("subway_grid_dataset:", subway_check.shape)
display(subway_check.head())

population_facility_dataset: (8568, 47)

,격자코드,lon,lat,생활인구_평균,생활인구_최대,생활인구_최소,생활인구_출근시간평균,생활인구_주간평균,생활인구_퇴근시간평균,생활인구_야간평균,...,여자 70세 이상,대피소수,대피소면적합,대피소유형수,병원수,응급병원수,병원종류수,상권수,상권대분류수,상권중분류수
0,다사52255325,126.960632,37.578526,33.402899,68.59,4.39,32.772222,47.761250,34.806667,20.382222,...,6.244783,1.0,4953.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
1,다사52255350,126.960616,37.580780,11.575000,20.34,5.40,10.963333,18.746250,11.626667,6.006000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,다사52255375,126.960599,37.583033,25.147500,44.22,11.75,23.823333,40.720000,25.263333,13.052000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,다사52505325,126.963463,37.578539,38.253542,75.01,9.75,36.258333,65.673125,40.540000,16.230500,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,다사52505350,126.963447,37.580792,826.548333,981.45,674.67,857.263333,702.906250,752.893333,938.344000,...,92.574167,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,4.0

subway_grid_dataset: (330, 61)

,격자코드,lon,lat,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,출근_승차합,출근_하차합,주간_승차합,주간_하차합,퇴근_승차합,퇴근_하차합,노선명목록,역사명목록,지하철역수,지하철노선수
0,다사38005325,126.799256,37.577679,7.798507,0.738806,2364.589552,242.074627,9895.925373,2660.253731,25965.731343,...,53964.052239,12761.835821,42722.216418,28485.776119,14358.134328,27134.462687,9호선,개화,1,1
1,다사38255150,126.802234,37.561923,34.164179,1.723881,4264.888060,6613.589552,9927.208955,33174.425373,26958.111940,...,98439.432836,154632.388060,388797.149254,393589.388060,191177.858209,114229.776119,"5호선, 9호선, 공항철도 1호선",김포공항,1,3
2,다사38505150,126.805065,37.561940,17.218750,4.093750,298.812500,2093.781250,638.718750,7636.031250,1640.531250,...,7394.687500,29289.218750,44909.187500,67111.406250,25119.937500,13983.062500,서해선,김포공항,1,1
3,다사38505275,126.804960,37.573206,1.455224,0.119403,4099.731343,301.783582,8240.373134,4089.656716,22808.671642,...,54787.358209,29448.626866,67308.761194,57476.708955,25501.097015,41594.373134,5호선,개화산,1,1
4,다사39005150,126.810726,37.561973,17.656716,0.417910,4109.798507,1617.432836,9139.783582,5826.082090,25000.276119,...,69767.171642,32872.686567,98651.500000,87236.507463,34301.373134,59390.552239,5호선,송정,1,1

In [ ]:
def dataset_overview(df, name):
    print(f"\n{'='*80}")
    print(f"[{name}]")
    print(f"{'='*80}")
    print("shape:", df.shape)
    print("\n[columns]")
    print(df.columns.tolist())

    print("\n[dtypes]")
    display(df.dtypes.to_frame("dtype"))

    print("\n[missing values]")
    missing = df.isnull().sum().sort_values(ascending=False)
    missing_ratio = (df.isnull().mean() * 100).sort_values(ascending=False)
    missing_df = pd.DataFrame({
        "missing_count": missing,
        "missing_ratio(%)": missing_ratio.round(2)
    })
    display(missing_df[missing_df["missing_count"] > 0])

    print("\n[numeric summary]")
    display(df.describe())

dataset_overview(population_facility_dataset, "population_facility_dataset")
dataset_overview(subway_grid_dataset, "subway_grid_dataset")

================================================================================
[population_facility_dataset]
================================================================================
shape: (8568, 47)

[columns]
['격자코드', 'lon', 'lat', '생활인구_평균', '생활인구_최대', '생활인구_최소', '생활인구_출근시간평균', '생활인구_주간평균', '생활인구_퇴근시간평균', '생활인구_야간평균', '남자 0~9세', '남자 10~14세', '남자 15~19세', '남자 20~24세', '남자 25~29세', '남자 30~34세', '남자 35~39세', '남자 40~44세', '남자 45~49세', '남자 50~54세', '남자 55~59세', '남자 60~64세', '남자 65~69세', '남자 70세 이상', '여자 0~9세', '여자 10~14세', '여자 15~19세', '여자 20~24세', '여자 25~29세', '여자 30~34세', '여자 35~39세', '여자 40~44세', '여자 45~49세', '여자 50~54세', '여자 55~59세', '여자 60~64세', '여자 65~69세', '여자 70세 이상', '대피소수', '대피소면적합', '대피소유형수', '병원수', '응급병원수', '병원종류수', '상권수', '상권대분류수', '상권중분류수']

[dtypes]

               dtype
격자코드          object
lon          float64
lat          float64
생활인구_평균      float64
생활인구_최대      float64
생활인구_최소      float64
생활인구_출근시간평균  float64
생활인구_주간평균    float64
생활인구_퇴근시간평균  float64
생활인구_야간평균    float64
남자 0~9세      float64
남자 10~14세    float64
남자 15~19세    float64
남자 20~24세    float64
남자 25~29세    float64
남자 30~34세    float64
남자 35~39세    float64
남자 40~44세    float64
남자 45~49세    float64
남자 50~54세    float64
남자 55~59세    float64
남자 60~64세    float64
남자 65~69세    float64
남자 70세 이상    float64
여자 0~9세      float64
여자 10~14세    float64
여자 15~19세    float64
여자 20~24세    float64
여자 25~29세    float64
여자 30~34세    float64
여자 35~39세    float64
여자 40~44세    float64
여자 45~49세    float64
여자 50~54세    float64
여자 55~59세    float64
여자 60~64세    float64
여자 65~69세    float64
여자 70세 이상    float64
대피소수         float64
대피소면적합       float64
대피소유형수       float64
병원수          float64
응급병원수        float64
병원종류수        float64
상권수          float64
상권대분류수       float64
상권중분류수       float64

[missing values]

             missing_count  missing_ratio(%)
남자 0~9세               4591             53.58
여자 0~9세               4331             50.55
여자 10~14세             3065             35.77
남자 10~14세             3011             35.14
여자 15~19세             2509             29.28
남자 15~19세             2464             28.76
남자 20~24세             2275             26.55
여자 20~24세             2213             25.83
여자 35~39세             1976             23.06
여자 30~34세             1969             22.98
여자 25~29세             1967             22.96
남자 35~39세             1927             22.49
남자 25~29세             1917             22.37
남자 30~34세             1830             21.36
여자 40~44세             1815             21.18
여자 65~69세             1795             20.95
남자 40~44세             1792             20.92
남자 65~69세             1773             20.69
여자 60~64세             1745             20.37
여자 45~49세             1743             20.34
남자 45~49세             1735             20.25
여자 55~59세             1668             19.47
남자 60~64세             1631             19.04
여자 50~54세             1620             18.91
남자 55~59세             1568             18.30
남자 50~54세             1568             18.30
여자 70세 이상             1400             16.34
남자 70세 이상             1391             16.23
생활인구_야간평균              305              3.56
생활인구_퇴근시간평균            291              3.40
생활인구_출근시간평균            283              3.30
생활인구_주간평균              229              2.67
생활인구_최대                200              2.33
생활인구_평균                200              2.33
생활인구_최소                200              2.33

[numeric summary]

,lon,lat,생활인구_평균,생활인구_최대,생활인구_최소,생활인구_출근시간평균,생활인구_주간평균,생활인구_퇴근시간평균,생활인구_야간평균,남자 0~9세,...,여자 70세 이상,대피소수,대피소면적합,대피소유형수,병원수,응급병원수,병원종류수,상권수,상권대분류수,상권중분류수
count,8568.000000,8568.000000,8368.000000,8368.000000,8368.000000,8285.000000,8339.000000,8277.000000,8263.000000,3977.000000,...,7168.000000,8568.000000,8568.000000,8568.000000,8568.000000,8568.000000,8568.000000,8568.000000,8568.000000,8568.000000
mean,126.991929,37.549060,1132.252176,1715.421007,669.353991,1131.065145,1217.919231,1153.957931,1084.007701,11.602399,...,107.015188,0.180906,1022.850315,0.160364,2.585901,0.008754,0.809757,62.432190,5.132236,16.312558
std,0.092025,0.057452,1359.287284,2171.090472,999.665480,1364.036385,1683.898955,1419.616762,1328.230250,9.395049,...,117.804778,0.439605,7547.819310,0.366965,7.402522,0.093155,1.250652,105.124817,3.901034,16.173273
min,126.765482,37.430248,4.033333,4.040000,4.000000,4.020000,4.000000,4.040000,4.010000,4.000000,...,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,126.920676,37.502121,70.691042,128.407500,8.830000,63.270000,77.666875,65.100000,56.395500,5.664000,...,14.911458,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
50%,127.003003,37.546494,665.084035,1106.165000,106.280000,675.363333,696.203000,668.003333,568.452000,8.146111,...,66.721275,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000,6.000000,12.000000
75%,127.064748,37.588005,1773.248125,2607.682500,1080.090000,1768.333333,1746.050000,1769.833333,1702.691500,13.581250,...,159.898229,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000,84.000000,9.000000,30.000000
max,127.181615,37.700460,15380.078333,56269.910000,9560.060000,14924.120000,26827.686250,14224.323333,11221.324000,124.397083,...,1013.801250,3.000000,378440.000000,1.000000,151.000000,1.000000,6.000000,1406.000000,10.000000,64.000000

================================================================================
[subway_grid_dataset]
================================================================================
shape: (330, 61)

[columns]
['격자코드', 'lon', 'lat', '04시-05시 승차인원', '04시-05시 하차인원', '05시-06시 승차인원', '05시-06시 하차인원', '06시-07시 승차인원', '06시-07시 하차인원', '07시-08시 승차인원', '07시-08시 하차인원', '08시-09시 승차인원', '08시-09시 하차인원', '09시-10시 승차인원', '09시-10시 하차인원', '10시-11시 승차인원', '10시-11시 하차인원', '11시-12시 승차인원', '11시-12시 하차인원', '12시-13시 승차인원', '12시-13시 하차인원', '13시-14시 승차인원', '13시-14시 하차인원', '14시-15시 승차인원', '14시-15시 하차인원', '15시-16시 승차인원', '15시-16시 하차인원', '16시-17시 승차인원', '16시-17시 하차인원', '17시-18시 승차인원', '17시-18시 하차인원', '18시-19시 승차인원', '18시-19시 하차인원', '19시-20시 승차인원', '19시-20시 하차인원', '20시-21시 승차인원', '20시-21시 하차인원', '21시-22시 승차인원', '21시-22시 하차인원', '22시-23시 승차인원', '22시-23시 하차인원', '23시-24시 승차인원', '23시-24시 하차인원', '00시-01시 승차인원', '00시-01시 하차인원', '01시-02시 승차인원', '01시-02시 하차인원', '02시-03시 승차인원', '02시-03시 하차인원', '03시-04시 승차인원', '03시-04시 하차인원', '출근_승차합', '출근_하차합', '주간_승차합', '주간_하차합', '퇴근_승차합', '퇴근_하차합', '노선명목록', '역사명목록', '지하철역수', '지하철노선수']

[dtypes]

                dtype
격자코드           object
lon           float64
lat           float64
04시-05시 승차인원  float64
04시-05시 하차인원  float64
...               ...
퇴근_하차합        float64
노선명목록          object
역사명목록          object
지하철역수           int64
지하철노선수          int64

[61 rows x 1 columns]

[missing values]

Empty DataFrame
Columns: [missing_count, missing_ratio(%)]
Index: []

[numeric summary]

,lon,lat,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,07시-08시 하차인원,...,03시-04시 승차인원,03시-04시 하차인원,출근_승차합,출근_하차합,주간_승차합,주간_하차합,퇴근_승차합,퇴근_하차합,지하철역수,지하철노선수
count,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,...,330.000000,330.000000,330.000000,3.300000e+02,3.300000e+02,3.300000e+02,3.300000e+02,3.300000e+02,330.000000,330.000000
mean,126.995150,37.549022,231.862158,3.982789,7554.403527,1930.851592,14875.978016,11829.566360,39618.133093,27636.571838,...,0.029294,0.149510,120234.980688,1.361063e+05,2.479720e+05,2.394235e+05,1.270657e+05,1.233334e+05,1.181818,1.112121
std,0.082563,0.048799,882.198517,8.460133,9241.210903,2016.354660,15265.737079,13824.570035,41792.854919,37213.088425,...,0.207076,0.632311,129828.767575,1.853689e+05,2.557597e+05,2.605632e+05,1.694109e+05,1.321769e+05,0.394070,0.334680
min,126.799256,37.434029,0.231343,0.022388,2.022388,8.052239,8.492537,56.641791,29.164179,27.164179,...,0.000000,0.000000,173.567164,3.358657e+02,8.957761e+02,5.711567e+02,4.830672e+02,7.370896e+01,1.000000,1.000000
25%,126.930196,37.511206,10.214598,0.345149,2328.953358,723.133517,5325.197761,4095.527985,13122.436092,7605.658582,...,0.000000,0.000000,44738.555970,3.405993e+04,9.224720e+04,8.221148e+04,2.939565e+04,4.700692e+04,1.000000,1.000000
50%,127.007526,37.547033,27.787313,0.966637,4735.205224,1308.339552,9782.496269,7501.078358,25853.172035,14877.570896,...,0.000000,0.000000,75375.599118,6.781399e+04,1.612705e+05,1.522882e+05,6.823146e+04,7.894882e+04,1.000000,1.000000
75%,127.056365,37.575612,107.496372,4.007463,9667.201766,2389.516791,18100.766791,13482.828641,49497.345149,32887.619403,...,0.007463,0.014925,148548.200680,1.574128e+05,3.030457e+05,2.885072e+05,1.399645e+05,1.492911e+05,1.000000,1.000000
max,127.175906,37.689306,10309.067164,83.694030,95426.521702,14838.209440,99361.378424,104442.742099,277151.929625,260347.371260,...,3.476190,7.667088,917005.681416,1.421012e+06,1.994995e+06,2.057482e+06,1.245679e+06,1.017988e+06,3.000000,3.000000

In [ ]:
print("[population_facility_dataset numeric describe]")
display(population_facility_dataset.describe().T)

print("[subway_grid_dataset numeric describe]")
display(subway_grid_dataset.describe().T)

[population_facility_dataset numeric describe]

,count,mean,std,min,25%,50%,75%,max
lon,8568.0,126.991929,0.092025,126.765482,126.920676,127.003003,127.064748,127.181615
lat,8568.0,37.549060,0.057452,37.430248,37.502121,37.546494,37.588005,37.700460
생활인구_평균,8368.0,1132.252176,1359.287284,4.033333,70.691042,665.084035,1773.248125,15380.078333
생활인구_최대,8368.0,1715.421007,2171.090472,4.040000,128.407500,1106.165000,2607.682500,56269.910000
생활인구_최소,8368.0,669.353991,999.665480,4.000000,8.830000,106.280000,1080.090000,9560.060000
생활인구_출근시간평균,8285.0,1131.065145,1364.036385,4.020000,63.270000,675.363333,1768.333333,14924.120000
생활인구_주간평균,8339.0,1217.919231,1683.898955,4.000000,77.666875,696.203000,1746.050000,26827.686250
생활인구_퇴근시간평균,8277.0,1153.957931,1419.616762,4.040000,65.100000,668.003333,1769.833333,14224.323333
생활인구_야간평균,8263.0,1084.007701,1328.230250,4.010000,56.395500,568.452000,1702.691500,11221.324000
남자 0~9세,3977.0,11.602399,9.395049,4.000000,5.664000,8.146111,13.581250,124.397083
남자 10~14세,5557.0,31.242776,39.054557,4.010000,8.030000,17.012500,38.087917,481.035417
남자 15~19세,6104.0,36.080425,52.256169,4.000000,9.180491,19.686617,41.162188,873.494000
남자 20~24세,6293.0,41.617960,57.885086,4.000000,11.119167,26.206667,50.659167,989.130833
남자 25~29세,6651.0,62.722712,70.918133,4.000000,14.019545,43.396042,83.827885,973.919167
남자 30~34세,6738.0,70.717302,84.468471,4.000000,14.511958,47.433317,95.595729,1363.085833
남자 35~39세,6641.0,59.441476,68.575503,4.000000,13.710417,41.574583,80.462917,1177.338750
남자 40~44세,6776.0,61.357061,70.843207,4.000000,13.413314,42.605521,82.840625,1134.424583
남자 45~49세,6833.0,58.775362,64.868423,4.000000,12.945417,41.289167,81.651250,867.300000
남자 50~54세,7000.0,61.535882,66.875822,4.000000,12.620828,44.317292,87.712292,1134.834167
남자 55~59세,7000.0,57.588047,57.533050,4.000000,12.286458,42.935417,83.164933,850.386667
남자 60~64세,6937.0,52.565806,50.126820,4.000000,11.707692,38.450833,77.124583,471.563750
남자 65~69세,6795.0,50.195983,48.366499,4.000000,11.507083,35.797500,72.972604,404.037083
남자 70세 이상,7177.0,82.316564,87.160172,4.000000,13.557500,54.695417,121.905417,1236.214167
여자 0~9세,4237.0,13.380192,11.805758,4.000000,5.720000,9.076000,16.013750,140.997083
여자 10~14세,5503.0,31.740942,40.045805,4.010000,7.944626,17.472083,38.647292,520.745000
여자 15~19세,6059.0,38.131854,59.060308,4.010000,9.569750,20.564583,41.684561,1447.805000
여자 20~24세,6355.0,52.561539,74.474336,4.000000,12.804118,32.431250,63.934583,1504.216667
여자 25~29세,6601.0,74.686406,91.091163,4.000000,15.721905,48.484706,97.567083,1531.482500
여자 30~34세,6599.0,74.264594,86.631408,4.000000,15.637798,50.448333,100.700261,1522.197917
여자 35~39세,6592.0,59.952029,64.731856,4.000000,13.544375,42.665297,83.688542,971.379286
여자 40~44세,6753.0,60.343734,64.315252,4.000000,12.628333,41.767917,84.527500,725.862708
여자 45~49세,6825.0,58.959379,62.541736,4.000000,12.184583,40.985417,82.707917,957.744583
여자 50~54세,6948.0,62.512267,63.774328,4.000000,12.388826,44.827917,90.753646,801.882917
여자 55~59세,6900.0,61.914374,62.257791,4.000000,12.317667,44.694792,89.719375,664.032083
여자 60~64세,6823.0,58.884158,59.095680,4.000000,11.855722,40.744583,85.958125,546.962500
여자 65~69세,6773.0,58.298231,58.874100,4.000000,11.857500,40.181875,84.951250,518.542917
여자 70세 이상,7168.0,107.015188,117.804778,4.000000,14.911458,66.721275,159.898229,1013.801250
대피소수,8568.0,0.180906,0.439605,0.000000,0.000000,0.000000,0.000000,3.000000
대피소면적합,8568.0,1022.850315,7547.819310,0.000000,0.000000,0.000000,0.000000,378440.000000
대피소유형수,8568.0,0.160364,0.366965,0.000000,0.000000,0.000000,0.000000,1.000000
병원수,8568.0,2.585901,7.402522,0.000000,0.000000,0.000000,2.000000,151.000000
응급병원수,8568.0,0.008754,0.093155,0.000000,0.000000,0.000000,0.000000,1.000000
병원종류수,8568.0,0.809757,1.250652,0.000000,0.000000,0.000000,1.000000,6.000000
상권수,8568.0,62.432190,105.124817,0.000000,1.000000,19.000000,84.000000,1406.000000
상권대분류수,8568.0,5.132236,3.901034,0.000000,1.000000,6.000000,9.000000,10.000000
상권중분류수,8568.0,16.312558,16.173273,0.000000,1.000000,12.000000,30.000000,64.000000

[subway_grid_dataset numeric describe]

,count,mean,std,min,25%,50%,75%,max
lon,330.0,126.995150,0.082563,126.799256,126.930196,127.007526,127.056365,1.271759e+02
lat,330.0,37.549022,0.048799,37.434029,37.511206,37.547033,37.575612,3.768931e+01
04시-05시 승차인원,330.0,231.862158,882.198517,0.231343,10.214598,27.787313,107.496372,1.030907e+04
04시-05시 하차인원,330.0,3.982789,8.460133,0.022388,0.345149,0.966637,4.007463,8.369403e+01
05시-06시 승차인원,330.0,7554.403527,9241.210903,2.022388,2328.953358,4735.205224,9667.201766,9.542652e+04
05시-06시 하차인원,330.0,1930.851592,2016.354660,8.052239,723.133517,1308.339552,2389.516791,1.483821e+04
06시-07시 승차인원,330.0,14875.978016,15265.737079,8.492537,5325.197761,9782.496269,18100.766791,9.936138e+04
06시-07시 하차인원,330.0,11829.566360,13824.570035,56.641791,4095.527985,7501.078358,13482.828641,1.044427e+05
07시-08시 승차인원,330.0,39618.133093,41792.854919,29.164179,13122.436092,25853.172035,49497.345149,2.771519e+05
07시-08시 하차인원,330.0,27636.571838,37213.088425,27.164179,7605.658582,14877.570896,32887.619403,2.603474e+05
08시-09시 승차인원,330.0,49232.772690,54781.754701,99.104478,18173.509328,30570.046347,59783.854478,3.818438e+05
08시-09시 하차인원,330.0,65206.374086,90992.624304,235.082090,15615.755910,31587.761194,75900.579584,6.620585e+05
09시-10시 승차인원,330.0,31384.074905,34494.575776,45.298507,12057.001866,21033.580258,37625.856343,2.656392e+05
09시-10시 하차인원,330.0,43263.347409,60535.699393,73.619403,10469.547999,21700.317489,48618.347182,4.986065e+05
10시-11시 승차인원,330.0,23795.877572,23655.251586,29.671642,9776.027985,16479.638060,28448.251866,1.809112e+05
10시-11시 하차인원,330.0,28013.696123,33511.993043,165.470149,7955.832090,16008.843284,33434.779884,2.300609e+05
11시-12시 승차인원,330.0,24332.464807,23809.139284,19.559701,10292.604478,16353.298507,30840.470598,1.827821e+05
11시-12시 하차인원,330.0,26165.146747,31342.145543,184.492537,7621.264925,15600.078358,30908.643657,2.384787e+05
12시-13시 승차인원,330.0,26802.478621,26277.154863,17.022388,10514.755597,17772.249017,34166.220805,1.994618e+05
12시-13시 하차인원,330.0,26948.394477,30631.255121,76.007463,8420.858209,16065.817164,32353.279851,2.318525e+05
13시-14시 승차인원,330.0,28547.868818,29383.439800,18.022388,10792.731343,18663.003731,35358.521692,2.254083e+05
13시-14시 하차인원,330.0,29314.889273,33121.688191,22.932836,9428.973881,17660.764925,34520.301684,2.462849e+05
14시-15시 승차인원,330.0,28729.026069,30748.027828,27.619403,10337.208955,18120.977612,34253.497693,2.333526e+05
14시-15시 하차인원,330.0,28450.820899,31812.195497,17.231343,9404.197761,17493.809701,33464.031716,2.455237e+05
15시-16시 승차인원,330.0,31987.547608,35159.666074,21.425373,10703.490672,19537.227612,38232.048507,2.671802e+05
15시-16시 하차인원,330.0,29530.162233,31944.643280,20.567164,10352.643657,18492.723881,36581.372915,2.615346e+05
16시-17시 승차인원,330.0,36898.739901,40309.434200,365.007463,12799.940299,22906.421642,43189.811567,3.082181e+05
16시-17시 하차인원,330.0,32302.750162,33936.931261,38.604478,12233.777985,21209.419797,40268.748420,2.843835e+05
17시-18시 승차인원,330.0,46878.021729,54861.354843,397.447761,14354.216418,28910.705224,56082.208955,3.976806e+05
17시-18시 하차인원,330.0,38697.642833,40526.706483,45.850746,14881.367537,25867.660448,48031.075643,3.270264e+05
18시-19시 승차인원,330.0,62384.319247,82689.044640,48.813433,15004.539179,32638.273567,69938.351714,5.957923e+05
18시-19시 하차인원,330.0,52910.572118,56084.783519,37.238806,20114.748134,35267.111940,64515.445896,4.472874e+05
19시-20시 승차인원,330.0,36285.325310,48987.721647,400.753731,8307.666045,19312.511114,38762.095832,3.732418e+05
19시-20시 하차인원,330.0,43720.309670,47345.690013,20.985075,16225.194652,27950.361940,53154.111510,3.532390e+05
20시-21시 승차인원,330.0,28396.035185,39908.869485,33.500000,6222.753731,14180.283582,31285.017084,3.403443e+05
20시-21시 하차인원,330.0,26702.477673,29434.542022,15.485075,9788.708955,16866.695047,31625.916045,2.174617e+05
21시-22시 승차인원,330.0,27099.416185,38596.848986,36.477612,5405.655271,12735.962687,29855.886194,3.014543e+05
21시-22시 하차인원,330.0,24013.209007,27310.152801,13.992537,8760.026119,15032.690299,27964.649492,2.023492e+05
22시-23시 승차인원,330.0,22213.566312,32830.879286,22.328358,3919.068949,10331.156764,25531.447761,2.317221e+05
22시-23시 하차인원,330.0,22558.863279,26731.620113,8.350746,7834.130597,14316.806555,26340.902985,2.009648e+05
23시-24시 승차인원,330.0,9466.645141,14149.376290,12.895522,1586.197761,4104.629308,10055.674147,1.024632e+05
23시-24시 하차인원,330.0,14292.684844,16537.845852,1.037313,5030.305970,9225.145522,16130.621269,1.286694e+05
00시-01시 승차인원,330.0,1231.797805,2000.195888,0.611940,188.869403,501.021736,1310.554647,1.533603e+04
00시-01시 하차인원,330.0,4286.248304,5134.565378,0.164179,1372.277985,2638.915307,5175.530590,4.613916e+04
01시-02시 승차인원,330.0,7.314990,13.836420,0.000000,0.947761,2.485075,6.677239,1.017307e+02
01시-02시 하차인원,330.0,184.548718,609.066775,0.000000,7.227612,26.466894,119.239169,8.355690e+03
02시-03시 승차인원,330.0,0.435584,2.091290,0.000000,0.007463,0.037313,0.139639,2.786567e+01
02시-03시 하차인원,330.0,2.268872,6.187813,0.000000,0.073620,0.529851,1.669776,7.845849e+01
03시-04시 승차인원,330.0,0.029294,0.207076,0.000000,0.000000,0.000000,0.007463,3.476190e+00
03시-04시 하차인원,330.0,0.149510,0.632311,0.000000,0.000000,0.000000,0.014925,7.667088e+00
출근_승차합,330.0,120234.980688,129828.767575,173.567164,44738.555970,75375.599118,148548.200680,9.170057e+05
출근_하차합,330.0,136106.293334,185368.884538,335.865672,34059.934701,67813.993056,157412.795282,1.421012e+06
주간_승차합,330.0,247972.025125,255759.663410,895.776119,92247.203358,161270.458955,303045.708955,1.994995e+06
주간_하차합,330.0,239423.502746,260563.157067,571.156716,82211.475746,152288.231343,288507.222797,2.057482e+06
퇴근_승차합,330.0,127065.679741,169410.938263,483.067164,29395.649254,68231.460575,139964.486443,1.245679e+06
퇴근_하차합,330.0,123333.359460,132176.896245,73.708955,47006.917910,78948.820896,149291.149254,1.017988e+06
지하철역수,330.0,1.181818,0.394070,1.000000,1.000000,1.000000,1.000000,3.000000e+00
지하철노선수,330.0,1.112121,0.334680,1.000000,1.000000,1.000000,1.000000,3.000000e+00

In [ ]:

population_facility_dataset.head()

,격자코드,lon,lat,생활인구_평균,생활인구_최대,생활인구_최소,생활인구_출근시간평균,생활인구_주간평균,생활인구_퇴근시간평균,생활인구_야간평균,...,여자 70세 이상,대피소수,대피소면적합,대피소유형수,병원수,응급병원수,병원종류수,상권수,상권대분류수,상권중분류수
0,다사52255325,126.960632,37.578526,33.402899,68.59,4.39,32.772222,47.761250,34.806667,20.382222,...,6.244783,1.0,4953.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
1,다사52255350,126.960616,37.580780,11.575000,20.34,5.40,10.963333,18.746250,11.626667,6.006000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,다사52255375,126.960599,37.583033,25.147500,44.22,11.75,23.823333,40.720000,25.263333,13.052000,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,다사52505325,126.963463,37.578539,38.253542,75.01,9.75,36.258333,65.673125,40.540000,16.230500,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
4,다사52505350,126.963447,37.580792,826.548333,981.45,674.67,857.263333,702.906250,752.893333,938.344000,...,92.574167,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,4.0